FLAG_EVENT_CODES = {
    "EVENT_GOT_KENYA",
    "EVENT_GAVE_KENYA",
    "EVENT_JASMINE_RETURNED_TO_GYM",
    "EVENT_DECIDED_TO_HELP_LANCE",
    "EVENT_CLEARED_ROCKET_HIDEOUT",
    "EVENT_CLEARED_RADIO_TOWER",
    "EVENT_BEAT_ELITE_FOUR",
    "EVENT_RESTORED_POWER_TO_KANTO",
    "EVENT_VIRIDIAN_GYM_BLUE",
    "EVENT_BEAT_RED",
    "EVENT_CLEARED_SLOWPOKE_WELL",
    "EVENT_HERDED_FARFETCHD",
    "EVENT_RELEASED_THE_BEASTS",
    "EVENT_BEAT_FALKNER",
    "EVENT_BEAT_BUGSY",
    "EVENT_BEAT_WHITNEY",
    "EVENT_BEAT_MORTY",
    "EVENT_BEAT_JASMINE",
    "EVENT_BEAT_CHUCK",
    "EVENT_BEAT_PRYCE",
    "EVENT_BEAT_CLAIR",
    "EVENT_BEAT_BROCK",
    "EVENT_BEAT_MISTY",
    "EVENT_BEAT_LTSURGE",
    "EVENT_BEAT_ERIKA",
    "EVENT_BEAT_JANINE",
    "EVENT_BEAT_SABRINA",
    "EVENT_BEAT_BLAINE",
    "EVENT_BEAT_BLUE",
    "EVENT_FAST_SHIP_FOUND_GIRL",
    "EVENT_FOUGHT_SNORLAX",
    "EVENT_MET_BILL"
}

FLAG_STATIC_CODES = {
    "EVENT_GOT_TOGEPI_EGG_FROM_ELMS_AIDE",
    "Sudowoodo_1",
    "RedGyarados_1",
    "Ho_Oh_1",
    "Lugia_1",
    "Suicune_1",
    "RocketHQElectrode1_1",
    "RocketHQElectrode2_1",
    "RocketHQElectrode3_1",
    "Shuckie_1",
    "Eevee_1",
    "Dratini_1",
    nil,
    "Tyrogue_1",
    "UnionCaveLapras_1",
    "Celebi_1"
}

-- RocketHQTrap1_1 = Voltorb
-- RocketHQTrap2_1 = Geodude
-- RocketHQTrap3_1 = Koffing
FLAG_TRAP_CODES = {
    "RocketHQTrap3_1",
    "RocketHQTrap1_1",
    "RocketHQTrap2_1",
    "RocketHQTrap1_1",
    "RocketHQTrap2_1",
    "RocketHQTrap3_1",
    "RocketHQTrap1_1",
    "RocketHQTrap3_1",
    "RocketHQTrap3_1",
    "RocketHQTrap1_1",
    "RocketHQTrap2_1",
    "RocketHQTrap2_1",
    "RocketHQTrap2_1",
    "RocketHQTrap3_1",
    "RocketHQTrap1_1",
    "RocketHQTrap3_1",
    "RocketHQTrap1_1",
    "RocketHQTrap2_1",
    "RocketHQTrap2_1",
    "RocketHQTrap1_1",
    "RocketHQTrap3_1",
    "RocketHQTrap1_1"
}

FLAG_ITEM_CODES = {
  {option="badges_off", codes={"ZEPHYR_BADGE"}},
  {option="badges_off", codes={"HIVE_BADGE"}},
  {option="badges_off", codes={"PLAIN_BADGE"}},
  {option="badges_off", codes={"FOG_BADGE"}},
  {option="badges_off", codes={"STORM_BADGE"}},
  {option="badges_off", codes={"MINERAL_BADGE"}},
  {option="badges_off", codes={"GLACIER_BADGE"}},
  {option="badges_off", codes={"RISING_BADGE"}},
  {option="badges_off", codes={"BOULDER_BADGE"}},
  {option="badges_off", codes={"CASCADE_BADGE"}},
  {option="badges_off", codes={"THUNDER_BADGE"}},
  {option="badges_off", codes={"RAINBOW_BADGE"}},
  {option="badges_off", codes={"SOUL_BADGE"}},
  {option="badges_off", codes={"MARSH_BADGE"}},
  {option="badges_off", codes={"VOLCANO_BADGE"}},
  {option="badges_off", codes={"EARTH_BADGE"}},

  {option="pokegear_off", codes={"RADIO_CARD"}},
  {option="pokegear_off", codes={"MAP_CARD"}},
  {option="pokegear_off", codes=nil},
  {option="pokegear_off", codes={"EXPN_CARD"}},
  {option="pokegear_off", codes={"POKE_GEAR"}},
  {option="pokegear_off", codes=nil},
  {option=nil, codes={"ESCAPE_ROPE"}},
  {option=nil, codes={"WATER_STONE"}},
}