FLAG_EVENT_1_CODES = {
    "EVENT_GOT_KENYA",
    "EVENT_GAVE_KENYA",
    "EVENT_JASMINE_RETURNED_TO_GYM",
    "EVENT_DECIDED_TO_HELP_LANCE",
    "EVENT_CLEARED_ROCKET_HIDEOUT",
    "EVENT_CLEARED_RADIO_TOWER",
    "EVENT_BEAT_ELITE_FOUR",
    "EVENT_RESTORED_POWER_TO_KANTO",
    "EVENT_VIRIDIAN_GYM_BLUE",
    "EVENT_BEAT_RED",
    "EVENT_CLEARED_SLOWPOKE_WELL",
    "EVENT_HERDED_FARFETCHD",
    "EVENT_RELEASED_THE_BEASTS",
    "EVENT_BEAT_FALKNER",
    "EVENT_BEAT_BUGSY",
    "EVENT_BEAT_WHITNEY",
    "EVENT_BEAT_MORTY",
    "EVENT_BEAT_JASMINE",
    "EVENT_BEAT_CHUCK",
    "EVENT_BEAT_PRYCE",
    "EVENT_BEAT_CLAIR",
    "EVENT_BEAT_BROCK",
    "EVENT_BEAT_MISTY",
    "EVENT_BEAT_LTSURGE",
    "EVENT_BEAT_ERIKA",
    "EVENT_BEAT_JANINE",
    "EVENT_BEAT_SABRINA",
    "EVENT_BEAT_BLAINE",
    "EVENT_BEAT_BLUE",
    "EVENT_FAST_SHIP_FOUND_GIRL",
    "EVENT_GOT_MYSTERY_EGG_FROM_MR_POKEMON",
    "EVENT_MET_BILL"
}

FLAG_EVENT_2_CODES = {
    "EVENT_SAW_SUICUNE_AT_CIANWOOD_CITY",
    "EVENT_SAW_SUICUNE_ON_ROUTE_42",
    "EVENT_SAW_SUICUNE_ON_ROUTE_36",
    "EVENT_BEAT_RIVAL_IN_MT_MOON",
    "EVENT_GOT_EON_MAIL_FROM_EUSINE",
    "EVENT_BEAT_CHERRYGROVE_RIVAL",
    "EVENT_BEAT_AZALEA_RIVAL",
    "EVENT_RIVAL_BURNED_TOWER",
    "EVENT_BEAT_GOLDENROD_UNDERGROUND_RIVAL",
    "EVENT_BEAT_VICTORY_ROAD_RIVAL",
    "EVENT_BEAT_RIVAL_IN_INDIGO_PLATEAU",
    "EVENT_ROUTE_24_ROCKET",
    "EVENT_GOT_ALL_UNOWN",
    "EVENT_OBTAINED_DIPLOMA",
    "EVENT_BEAT_ROCKET_EXECUTIVEM_3",
    "ENGINE_UNLOCKED_UNOWNS_A_TO_K",
    "ENGINE_UNLOCKED_UNOWNS_L_TO_R",
    "ENGINE_UNLOCKED_UNOWNS_S_TO_W",
    "ENGINE_UNLOCKED_UNOWNS_X_TO_Z",
    "EVENT_GAVE_MYSTERY_EGG_TO_ELM"
}

FLAG_STATIC_CODES = {
    "EVENT_GOT_TOGEPI_EGG_FROM_ELMS_AIDE",
    "Static_Sudowoodo",
    "Static_RedGyarados",
    "Static_Ho_Oh",
    "Static_Lugia",
    "Static_Suicune",
    "Static_RocketHQElectrode1",
    "Static_RocketHQElectrode2",
    "Static_RocketHQElectrode3",
    "Static_Shuckie",
    "Static_Eevee",
    "Static_Dratini",
    "dummy", -- this is the Togepi Egg Hatch. Technically this locks a check but we'll just use the event where you get it
    "Static_Tyrogue",
    "Static_UnionCaveLapras",
    "Static_Celebi",
    "EVENT_GOT_ODD_EGG",
    "Static_GoldenrodGameCorner1",
    "Static_GoldenrodGameCorner2",
    "Static_GoldenrodGameCorner3",
    "Static_CeladonGameCornerPrizeRoom1",
    "Static_CeladonGameCornerPrizeRoom2",
    "Static_CeladonGameCornerPrizeRoom3",
    "Static_Snorlax"
}

-- RocketHQTrap1_1 = Voltorb
-- RocketHQTrap2_1 = Geodude
-- RocketHQTrap3_1 = Koffing
FLAG_ROCKETTRAPS_CODES = {
    "Static_RocketHQTrap3",
    "Static_RocketHQTrap1",
    "Static_RocketHQTrap2",
    "Static_RocketHQTrap1",
    "Static_RocketHQTrap2",
    "Static_RocketHQTrap3",
    "Static_RocketHQTrap1",
    "Static_RocketHQTrap3",
    "Static_RocketHQTrap3",
    "Static_RocketHQTrap1",
    "Static_RocketHQTrap2",
    "Static_RocketHQTrap2",
    "Static_RocketHQTrap2",
    "Static_RocketHQTrap3",
    "Static_RocketHQTrap1",
    "Static_RocketHQTrap3",
    "Static_RocketHQTrap1",
    "Static_RocketHQTrap2",
    "Static_RocketHQTrap2",
    "Static_RocketHQTrap1",
    "Static_RocketHQTrap3",
    "Static_RocketHQTrap1"
}

FLAG_TRADE_CODES = {
    "TRADE_MIKE",
    "TRADE_KYLE",
    "TRADE_TIM",
    "TRADE_EMY",
    "TRADE_CHRIS",
    "TRADE_KIM",
    "TRADE_FOREST"
}

FLAG_ITEM_CODES = {
  {option="badges_off", codes={"ZEPHYR_BADGE"}},
  {option="badges_off", codes={"HIVE_BADGE"}},
  {option="badges_off", codes={"PLAIN_BADGE"}},
  {option="badges_off", codes={"FOG_BADGE"}},
  {option="badges_off", codes={"STORM_BADGE"}},
  {option="badges_off", codes={"MINERAL_BADGE"}},
  {option="badges_off", codes={"GLACIER_BADGE"}},
  {option="badges_off", codes={"RISING_BADGE"}},
  {option="badges_off", codes={"BOULDER_BADGE"}},
  {option="badges_off", codes={"CASCADE_BADGE"}},
  {option="badges_off", codes={"THUNDER_BADGE"}},
  {option="badges_off", codes={"RAINBOW_BADGE"}},
  {option="badges_off", codes={"SOUL_BADGE"}},
  {option="badges_off", codes={"MARSH_BADGE"}},
  {option="badges_off", codes={"VOLCANO_BADGE"}},
  {option="badges_off", codes={"EARTH_BADGE"}},
  {option="pokegear_off", codes={"RADIO_CARD"}},
  {option="pokegear_off", codes={"MAP_CARD"}},
  {option="pokegear_off", codes={"PHONE_CARD"}},
  {option="pokegear_off", codes={"EXPN_CARD"}},
  {option="pokegear_off", codes={"POKE_GEAR"}},
  {option="randomize_pokedex_vanilla", codes={"POKEDEX"}},
  {option=nil, codes={"ESCAPE_ROPE"}},
  {option=nil, codes={"WATER_STONE"}},
  {option="badges_off", codes={"RISING_BADGE"}},
  {option="berries_off", codes={"RED_APRICORN"}},
  {option="berries_off", codes={"BLU_APRICORN"}},
  {option="berries_off", codes={"YLW_APRICORN"}},
  {option="berries_off", codes={"GRN_APRICORN"}},
  {option="berries_off", codes={"WHT_APRICORN"}},
  {option="berries_off", codes={"BLK_APRICORN"}},
  {option="berries_off", codes={"PNK_APRICORN"}},
}

FLAG_SHOP_K_CODES = {
    "EVENT_SEEN_MART_VIRIDIAN",
    "EVENT_SEEN_MART_PEWTER",
    "EVENT_SEEN_MART_MT_MOON",
    "EVENT_SEEN_MART_CERULEAN",
    "EVENT_SEEN_MART_VERMILION",
    "EVENT_SEEN_MART_LAVENDER",
    "EVENT_SEEN_MART_SAFFRON",
    "EVENT_SEEN_MART_CELADON_2F_1",
    "EVENT_SEEN_MART_CELADON_2F_2",
    "EVENT_SEEN_MART_CELADON_3F",
    "EVENT_SEEN_MART_CELADON_4F",
    "EVENT_SEEN_MART_CELADON_5F_1",
    "EVENT_SEEN_MART_CELADON_5F_2",
    "EVENT_SEEN_MART_CELADON_VENDING_MACHINE",
    "EVENT_SEEN_MART_FUCHSIA",
    "EVENT_SEEN_MART_INDIGO_PLATEAU",
}

FLAG_SHOP_J_CODES = {
    "EVENT_SEEN_MART_CHERRYGROVE",
    "EVENT_SEEN_MART_VIOLET",
    "EVENT_SEEN_MART_AZALEA",
    "EVENT_SEEN_MART_KURTS_BALLS",
    "EVENT_SEEN_MART_CIANWOOD",
    "EVENT_SEEN_MART_GOLDENROD_2F_1",
    "EVENT_SEEN_MART_GOLDENROD_2F_2",
    "EVENT_SEEN_MART_GOLDENROD_3F",
    "EVENT_SEEN_MART_GOLDENROD_4F",
    "EVENT_SEEN_MART_GOLDENROD_5F",
    "EVENT_SEEN_MART_GOLDENROD_VENDING_MACHINE",
    "EVENT_SEEN_MART_ROOFTOP_SALE",
    "EVENT_SEEN_MART_UNDERGROUND",
    "EVENT_SEEN_MART_BARGAIN_SHOP",
    "EVENT_SEEN_MART_BLUE_CARD",
    "EVENT_SEEN_MART_OLIVINE",
    "EVENT_SEEN_MART_ECRUTEAK",
    "EVENT_SEEN_MART_MAHOGANY_1",
    "EVENT_SEEN_MART_MAHOGANY_2",
    "EVENT_SEEN_MART_BLACKTHORN",
}

SHOP_MAPPING = {
    ["EVENT_SEEN_MART_VIRIDIAN"] = "@JohtoKanto/Viridian City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_PEWTER"] = "@JohtoKanto/Pewter City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_MT_MOON"] = "@JohtoKanto/Mount Moon/Square - Gift Shop - Shop Items",
    ["EVENT_SEEN_MART_CERULEAN"] = "@JohtoKanto//Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_VERMILION"] = "@JohtoKanto/Cerulean City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_LAVENDER"] = "@JohtoKanto/Lavender Town/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_SAFFRON"] = "@JohtoKanto/Saffron City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_CELADON_2F_1"] = "@JohtoKanto/Celadon City/Dept. Store 2F - Right Salesman - Shop Items",
    ["EVENT_SEEN_MART_CELADON_2F_2"] = "@JohtoKanto/Celadon City/Dept. Store 2F - Left Salesman - Shop Items",
    ["EVENT_SEEN_MART_CELADON_3F"] = "@JohtoKanto/Celadon City/Dept. Store 3F - TM Shop - Shop Items",
    ["EVENT_SEEN_MART_CELADON_4F"] = "@JohtoKanto/Celadon City/Dept. Store 4F - Mail Shop - Shop Items",
    ["EVENT_SEEN_MART_CELADON_5F_1"] = "@JohtoKanto/Celadon City/Dept. Store 5F - Vitamin Shop - Shop Items",
    ["EVENT_SEEN_MART_CELADON_5F_2"] = "@JohtoKanto/Celadon City/Dept. Store 5F - X Items Shop - Shop Items",
    ["EVENT_SEEN_MART_CELADON_VENDING_MACHINE"] = "@JohtoKanto/Celadon City/Dept. Store 6F - Vending Machine - Shop Items",
    ["EVENT_SEEN_MART_FUCHSIA"] = "@JohtoKanto/Fuchsia City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_INDIGO_PLATEAU"] = "@JohtoKanto/Indigo Plateau/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_CHERRYGROVE"] = "@JohtoKanto/Cherrygrove City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_VIOLET"] = "@JohtoKanto/Violet City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_AZALEA"] = "@JohtoKanto/Azalea Town/Poke Mart - Shop Items",
    --["EVENT_SEEN_MART_KURTS_BALLS"] = "@JohtoKanto//Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_CIANWOOD"] = "@JohtoKanto/Cianwood City/Pharmacy - Shop Items",
    ["EVENT_SEEN_MART_GOLDENROD_2F_1"] = "@JohtoKanto/Goldenrod City/Dept. Store 2F - Top Salesman - Shop Items",
    ["EVENT_SEEN_MART_GOLDENROD_2F_2"] = "@JohtoKanto/Goldenrod City/Dept. Store 2F - Bottom Salesman - Shop Items",
    ["EVENT_SEEN_MART_GOLDENROD_3F"] = "@JohtoKanto/Goldenrod City/Dept. Store 3F - X Items Shop - Shop Items",
    ["EVENT_SEEN_MART_GOLDENROD_4F"] = "@JohtoKanto/Goldenrod City/Dept. Store 4F - Vitamin Shop - Shop Items",
    ["EVENT_SEEN_MART_GOLDENROD_5F"] = "@JohtoKanto/Goldenrod City/Dept. Store 5F - TM Shop - Shop Items",
    ["EVENT_SEEN_MART_GOLDENROD_VENDING_MACHINE"] = "@JohtoKanto/Goldenrod City/Dept. Store 6F - Vending Machine - Shop Items",
    ["EVENT_SEEN_MART_ROOFTOP_SALE"] = "@JohtoKanto/Goldenrod City/Dept. Store 2F - Top Salesman - Shop Items",
    ["EVENT_SEEN_MART_UNDERGROUND"] = "@JohtoKanto/Goldenrod Underground/Herb Shop - Shop Items",
    ["EVENT_SEEN_MART_BARGAIN_SHOP"] = "@JohtoKanto/Goldenrod Underground/Bargain Shop - Shop Items",
    --["EVENT_SEEN_MART_BLUE_CARD"] = "@JohtoKanto//Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_OLIVINE"] = "@JohtoKanto/Olivine City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_ECRUTEAK"] = "@JohtoKanto/Ecruteak City/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_MAHOGANY_1"] = "@JohtoKanto/Mahogany Town/Rocket Shop - Shop Items",
    ["EVENT_SEEN_MART_MAHOGANY_2"] = "@JohtoKanto/Mahogany Town/Poke Mart - Shop Items",
    ["EVENT_SEEN_MART_BLACKTHORN"] = "@JohtoKanto/Blackthorn City/Poke Mart - Shop Items",
}