FLAG_EVENT_CODES = {
    "EVENT_GOT_KENYA",
    "EVENT_GAVE_KENYA",
    "EVENT_JASMINE_RETURNED_TO_GYM",
    "EVENT_DECIDED_TO_HELP_LANCE",
    "EVENT_CLEARED_ROCKET_HIDEOUT",
    "EVENT_CLEARED_RADIO_TOWER",
    "EVENT_BEAT_ELITE_FOUR",
    "EVENT_RESTORED_POWER_TO_KANTO",
    "EVENT_VIRIDIAN_GYM_BLUE",
    "EVENT_BEAT_RED",
    "EVENT_CLEARED_SLOWPOKE_WELL",
    "EVENT_HERDED_FARFETCHD",
    "EVENT_RELEASED_THE_BEASTS",
    "EVENT_BEAT_FALKNER",
    "EVENT_BEAT_BUGSY",
    "EVENT_BEAT_WHITNEY",
    "EVENT_BEAT_MORTY",
    "EVENT_BEAT_JASMINE",
    "EVENT_BEAT_CHUCK",
    "EVENT_BEAT_PRYCE",
    "EVENT_BEAT_CLAIR",
    "EVENT_BEAT_BROCK",
    "EVENT_BEAT_MISTY",
    "EVENT_BEAT_LTSURGE",
    "EVENT_BEAT_ERIKA",
    "EVENT_BEAT_JANINE",
    "EVENT_BEAT_SABRINA",
    "EVENT_BEAT_BLAINE",
    "EVENT_BEAT_BLUE",
    "EVENT_FAST_SHIP_FOUND_GIRL",
    "Snorlax",
    "EVENT_MET_BILL"
}

FLAG_STATIC_CODES = {
    "EVENT_GOT_TOGEPI_EGG_FROM_ELMS_AIDE",
    "Static_Sudowoodo",
    "Static_RedGyarados",
    "Static_Ho_Oh",
    "Static_Lugia",
    "Static_Suicune",
    "Static_RocketHQElectrode1",
    "Static_RocketHQElectrode2",
    "Static_RocketHQElectrode3",
    "Static_Shuckie",
    "Static_Eevee",
    "Static_Dratini",
    "dummy", -- This is Togepi Egg hatched but we don't track Egg hatches
    "Static_Tyrogue",
    "Static_UnionCaveLapras",
    "Static_Celebi",
    "EVENT_GOT_ODD_EGG",
    "Static_GoldenrodGameCorner1",
    "Static_GoldenrodGameCorner2",
    "Static_GoldenrodGameCorner3",
    "Static_CeladonGameCornerPrizeRoom1",
    "Static_CeladonGameCornerPrizeRoom2",
    "Static_CeladonGameCornerPrizeRoom3"
}

-- RocketHQTrap1_1 = Voltorb
-- RocketHQTrap2_1 = Geodude
-- RocketHQTrap3_1 = Koffing
FLAG_ROCKETTRAPS_CODES = {
    "RocketHQTrap3",
    "RocketHQTrap1",
    "RocketHQTrap2",
    "RocketHQTrap1",
    "RocketHQTrap2",
    "RocketHQTrap3",
    "RocketHQTrap1",
    "RocketHQTrap3",
    "RocketHQTrap3",
    "RocketHQTrap1",
    "RocketHQTrap2",
    "RocketHQTrap2",
    "RocketHQTrap2",
    "RocketHQTrap3",
    "RocketHQTrap1",
    "RocketHQTrap3",
    "RocketHQTrap1",
    "RocketHQTrap2",
    "RocketHQTrap2",
    "RocketHQTrap1",
    "RocketHQTrap3",
    "RocketHQTrap1"
}

FLAG_ITEM_CODES = {
  {option="badges_off", codes={"ZEPHYR_BADGE"}},
  {option="badges_off", codes={"HIVE_BADGE"}},
  {option="badges_off", codes={"PLAIN_BADGE"}},
  {option="badges_off", codes={"FOG_BADGE"}},
  {option="badges_off", codes={"STORM_BADGE"}},
  {option="badges_off", codes={"MINERAL_BADGE"}},
  {option="badges_off", codes={"GLACIER_BADGE"}},
  {option="badges_off", codes={"RISING_BADGE"}},
  {option="badges_off", codes={"BOULDER_BADGE"}},
  {option="badges_off", codes={"CASCADE_BADGE"}},
  {option="badges_off", codes={"THUNDER_BADGE"}},
  {option="badges_off", codes={"RAINBOW_BADGE"}},
  {option="badges_off", codes={"SOUL_BADGE"}},
  {option="badges_off", codes={"MARSH_BADGE"}},
  {option="badges_off", codes={"VOLCANO_BADGE"}},
  {option="badges_off", codes={"EARTH_BADGE"}},

  {option="pokegear_off", codes={"RADIO_CARD"}},
  {option="pokegear_off", codes={"MAP_CARD"}},
  {option="pokegear_off", codes=nil},
  {option="pokegear_off", codes={"EXPN_CARD"}},
  {option="pokegear_off", codes={"POKE_GEAR"}},
  {option="pokegear_off", codes=nil},
  {option=nil, codes={"ESCAPE_ROPE"}},
  {option=nil, codes={"WATER_STONE"}},
  
  {option="badges_off", codes={"RISING_BADGE"}},
}