MAP_MAPPING =  {
  [1] =  {
    [1] =  {"Johto Cities", "Olivine City", "PokeCenter"},              --OLIVINE_POKECENTER_1F
    [2] =  {"Johto Cities", "Olivine City", "Gym"},                     --OLIVINE_GYM
    [3] =  {"Johto Cities", "Olivine City", "Tim's House"},             --OLIVINE_TIMS_HOUSE
    [4] =  {""},                                                        --OLIVINE_HOUSE_BETA [does not exist]
    [5] =  {"Johto Cities", "Olivine City", "Punishment Speech House"}, --OLIVINE_PUNISHMENT_SPEECH_HOUSE
    [6] =  {"Johto Cities", "Olivine City", "Good Rod House"},          --OLIVINE_GOOD_ROD_HOUSE
    [7] =  {"Johto Cities", "Olivine City", "Cafe"},                    --OLIVINE_CAFE
    [8] =  {"Johto Cities", "Olivine City", "Mart"},                    --OLIVINE_MART
    [9] =  {"Johto Routes", "Route 38", "Ecruteak Gate"},               --ROUTE_38_ECRUTEAK_GATE
    [10] = {"Johto Routes", "Route 39", "Barn"},                        --ROUTE_39_BARN
    [11] = {"Johto Routes", "Route 39", "Farmhouse"},                   --ROUTE_39_FARMHOUSE
    [12] = {"Johto Routes", "Route 38", "Route"},                       --ROUTE_38
    [13] = {"Johto Routes", "Route 39", "Route"},                       --ROUTE_39
    [14] = {"Johto Cities", "Olivine City", "City"},                    --OLIVINE_CITY
  },
  [2] =  {
    [1] =  {"Johto Cities", "Mahogany Town", "Gyarados Speech House"}, --MAHOGANY_RED_GYARADOS_SPEECH_HOUSE
    [2] =  {"Johto Cities", "Mahogany Town", "Gym"},                   --MAHOGANY_GYM
    [3] =  {"Johto Cities", "Mahogany Town", "PokeCenter"},            --MAHOGANY_POKECENTER_1F
    [4] =  {"Johto Routes", "Route 42", "Ecruteak Gate"},              --ROUTE_42_ECRUTEAK_GATE
    [5] =  {"Johto Routes", "Route 42", "Route"},                      --ROUTE_42
    [6] =  {"Johto Routes", "Route 44"},                               --ROUTE_44
    [7] =  {"Johto Cities", "Mahogany Town", "Town"},                  --MAHOGANY_TOWN
  },
  [3] =  {
    [1] =  {"Johto Cities", "Violet City", "Sprout Tower", "1F"},               --SPROUT_TOWER_1F
    [2] =  {"Johto Cities", "Violet City", "Sprout Tower", "2F"},               --SPROUT_TOWER_2F
    [3] =  {"Johto Cities", "Violet City", "Sprout Tower", "3F"},               --SPROUT_TOWER_3F
    [4] =  {"Johto Cities", "Ecruteak City", "Tin Tower", "1F"},                --TIN_TOWER_1F
    [5] =  {"Johto Cities", "Ecruteak City", "Tin Tower", "2F"},                --TIN_TOWER_2F
    [6] =  {"Johto Cities", "Ecruteak City", "Tin Tower", "3F"},                --TIN_TOWER_3F
    [7] =  {"Johto Cities", "Ecruteak City", "Tin Tower", "4F"},                --TIN_TOWER_4F
    [8] =  {"Johto Cities", "Ecruteak City", "Tin Tower", "5F"},                --TIN_TOWER_5F
    [9] =  {"Johto Cities", "Ecruteak City", "Tin Tower", "6F"},                --TIN_TOWER_6F
    [10] = {"Johto Cities", "Ecruteak City", "Tin Tower", "7F"},                --TIN_TOWER_7F
    [11] = {"Johto Cities", "Ecruteak City", "Tin Tower", "8F"},                --TIN_TOWER_8F
    [12] = {"Johto Cities", "Ecruteak City", "Tin Tower", "9F"},                --TIN_TOWER_9F
    [13] = {"Johto Cities", "Ecruteak City", "Burned Tower", "1F"},             --BURNED_TOWER_1F
    [14] = {"Johto Cities", "Ecruteak City", "Burned Tower", "B1F"},            --BURNED_TOWER_B1F
    [15] = {"Johto Dungeons", "National Park"},                                 --NATIONAL_PARK
    [16] = {"Johto Dungeons", "National Park"},                                 --NATIONAL_PARK_BUG_CONTEST
    [17] = {"Johto Cities", "Goldenrod City", "Radio Tower", "1F"},             --RADIO_TOWER_1F
    [18] = {"Johto Cities", "Goldenrod City", "Radio Tower", "2F"},             --RADIO_TOWER_2F
    [19] = {"Johto Cities", "Goldenrod City", "Radio Tower", "3F"},             --RADIO_TOWER_3F
    [20] = {"Johto Cities", "Goldenrod City", "Radio Tower", "4F"},             --RADIO_TOWER_4F
    [21] = {"Johto Cities", "Goldenrod City", "Radio Tower", "5F"},             --RADIO_TOWER_5F
    [22] = {"Johto Dungeons", "Ruins of Alph", "Outside"},                      --RUINS_OF_ALPH_OUTSIDE
    [23] = {"Johto Dungeons", "Ruins of Alph", "Ho-Oh Chamber"},                --RUINS_OF_ALPH_HO_OH_CHAMBER
    [24] = {"Johto Dungeons", "Ruins of Alph", "Kabuto Chamber"},               --RUINS_OF_ALPH_KABUTO_CHAMBER
    [25] = {"Johto Dungeons", "Ruins of Alph", "Omanyte Chamber"},              --RUINS_OF_ALPH_OMANYTE_CHAMBER
    [26] = {"Johto Dungeons", "Ruins of Alph", "Aerodactyl Chamber"},           --RUINS_OF_ALPH_AERODACTYL_CHAMBER
    [27] = {"Johto Dungeons", "Ruins of Alph", "Inner Chamber"},                --RUINS_OF_ALPH_INNER_CHAMBER
    [28] = {"Johto Dungeons", "Ruins of Alph", "Research Center"},              --RUINS_OF_ALPH_RESEARCH_CENTER
    [29] = {"Johto Dungeons", "Ruins of Alph", "Ho-Oh Item Room"},              --RUINS_OF_ALPH_HO_OH_ITEM_ROOM
    [30] = {"Johto Dungeons", "Ruins of Alph", "Kabuto Item Room"},             --RUINS_OF_ALPH_KABUTO_ITEM_ROOM
    [31] = {"Johto Dungeons", "Ruins of Alph", "Omanyte Item Room"},            --RUINS_OF_ALPH_OMANYTE_ITEM_ROOM
    [32] = {"Johto Dungeons", "Ruins of Alph", "Aerodactyl Item Room"},         --RUINS_OF_ALPH_AERODACTYL_ITEM_ROOM
    [33] = {"Johto Dungeons", "Ruins of Alph", "Ho-Oh Word Room"},              --RUINS_OF_ALPH_HO_OH_WORD_ROOM
    [34] = {"Johto Dungeons", "Ruins of Alph", "Kabuto Word Room"},             --RUINS_OF_ALPH_KABUTO_WORD_ROOM
    [35] = {"Johto Dungeons", "Ruins of Alph", "Omanyte Word Room"},            --RUINS_OF_ALPH_OMANYTE_WORD_ROOM
    [36] = {"Johto Dungeons", "Ruins of Alph", "Aerodactyl Word Room"},         --RUINS_OF_ALPH_AERODACTYL_WORD_ROOM
    [37] = {"Johto Dungeons", "Union Cave", "Union Cave 1F"},                   --UNION_CAVE_1F
    [38] = {"Johto Dungeons", "Union Cave", "Union Cave B1F"},                  --UNION_CAVE_B1F
    [39] = {"Johto Dungeons", "Union Cave", "Union Cave B2F"},                  --UNION_CAVE_B2F
    [40] = {"Johto Cities", "Azalea Town", "Slowpoke Well", "B1F"},             --SLOWPOKE_WELL_B1F
    [41] = {"Johto Cities", "Azalea Town", "Slowpoke Well", "B2F"},             --SLOWPOKE_WELL_B2F
    [42] = {"Johto Cities", "Olivine City", "Lighthouse", "1F"},                --OLIVINE_LIGHTHOUSE_1F
    [43] = {"Johto Cities", "Olivine City", "Lighthouse", "2F"},                --OLIVINE_LIGHTHOUSE_2F
    [44] = {"Johto Cities", "Olivine City", "Lighthouse", "3F"},                --OLIVINE_LIGHTHOUSE_3F
    [45] = {"Johto Cities", "Olivine City", "Lighthouse", "4F"},                --OLIVINE_LIGHTHOUSE_4F
    [46] = {"Johto Cities", "Olivine City", "Lighthouse", "5F"},                --OLIVINE_LIGHTHOUSE_5F
    [47] = {"Johto Cities", "Olivine City", "Lighthouse", "6F"},                --OLIVINE_LIGHTHOUSE_6F
    [48] = {"Johto Cities", "Mahogany Town", "Mart"},                           --MAHOGANY_MART_1F
    [49] = {"Johto Cities", "Mahogany Town", "Rocket HQ", "B1F"},               --TEAM_ROCKET_BASE_B1F
    [50] = {"Johto Cities", "Mahogany Town", "Rocket HQ", "B2F"},               --TEAM_ROCKET_BASE_B2F
    [51] = {"Johto Cities", "Mahogany Town", "Rocket HQ", "B3F"},               --TEAM_ROCKET_BASE_B3F
    [52] = {"Johto Dungeons", "Ilex Forest"},                                   --ILEX_FOREST
    [53] = {"Johto Cities", "Goldenrod City", "Underground", "B1F"},            --GOLDENROD_UNDERGROUND
    [54] = {"Johto Cities", "Goldenrod City", "Underground", "B2F"},            --GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES
    [55] = {"Johto Cities", "Goldenrod City", "Dept. Store", "B1F"},            --GOLDENROD_DEPT_STORE_B1F
    [56] = {"Johto Cities", "Goldenrod City", "Underground", "Warehouse"},      --GOLDENROD_UNDERGROUND_WAREHOUSE
    [57] = {"Johto Dungeons", "Mt. Mortar", "Mt. Mortar 1F - Outside"},         --MOUNT_MORTAR_1F_OUTSIDE
    [58] = {"Johto Dungeons", "Mt. Mortar", "Mt. Mortar 1F - Inside"},          --MOUNT_MORTAR_1F_INSIDE
    [59] = {"Johto Dungeons", "Mt. Mortar", "Mt. Mortar 2F"},                   --MOUNT_MORTAR_2F_INSIDE
    [60] = {"Johto Dungeons", "Mt. Mortar", "Mt. Mortar B1F"},                  --MOUNT_MORTAR_B1F
    [61] = {"Johto Dungeons", "Ice Path", "Ice Path 1F"},                       --ICE_PATH_1F
    [62] = {"Johto Dungeons", "Ice Path", "Ice Path B1F"},                      --ICE_PATH_B1F
    [63] = {"Johto Dungeons", "Ice Path", "Ice Path B2F - Mahogany Side"},      --ICE_PATH_B2F_MAHOGANY_SIDE
    [64] = {"Johto Dungeons", "Ice Path", "Ice Path B2F - Blackthorn Side"},    --ICE_PATH_B2F_BLACKTHORN_SIDE
    [65] = {"Johto Dungeons", "Ice Path", "Ice Path B3F"},                      --ICE_PATH_B3F
    [66] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands 1F"},             --WHIRL_ISLAND_NW
    [67] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands 1F"},             --WHIRL_ISLAND_NE
    [68] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands 1F"},             --WHIRL_ISLAND_SW
    [69] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands Cave"},           --WHIRL_ISLAND_CAVE
    [70] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands 1F"},             --WHIRL_ISLAND_SE
    [71] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands B1F"},            --WHIRL_ISLAND_B1F
    [72] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands B2F"},            --WHIRL_ISLAND_B2F
    [73] = {"Johto Dungeons", "Whirl Islands", "Whirl Islands Lugia Chamber"},  --WHIRL_ISLAND_LUGIA_CHAMBER
    [74] = {"Johto Dungeons", "Silver Cave", "1F"},                             --SILVER_CAVE_ROOM_1
    [75] = {"Johto Dungeons", "Silver Cave", "2F"},                             --SILVER_CAVE_ROOM_2
    [76] = {"Johto Dungeons", "Silver Cave", "3F"},                             --SILVER_CAVE_ROOM_3
    [77] = {"Johto Dungeons", "Silver Cave", "2F"},                             --SILVER_CAVE_ITEM_ROOMS
    [78] = {"Johto Dungeons", "Dark Cave", "Dark Cave - Violet Entrance"},      --DARK_CAVE_VIOLET_ENTRANCE
    [79] = {"Johto Dungeons", "Dark Cave", "Dark Cave - Blackthorn Entrance"},  --DARK_CAVE_BLACKTHORN_ENTRANCE
    [80] = {"Johto Cities", "Blackthorn City", "Dragons Den", "1F"},            --DRAGONS_DEN_1F
    [81] = {"Johto Cities", "Blackthorn City", "Dragons Den", "B1F"},           --DRAGONS_DEN_B1F
    [82] = {"Johto Cities", "Blackthorn City", "Dragons Den", "Dragon Shrine"}, --DRAGON_SHRINE
    [83] = {"Johto Dungeons", "Tohjo Falls"},                                   --TOHJO_FALLS
    [84] = {"Kanto Dungeons", "Digletts Cave"},                                 --DIGLETTS_CAVE
    [85] = {"Kanto Dungeons", "Mount Moon", "Inside"},                          --MOUNT_MOON
    [86] = {"Kanto Dungeons", "Underground Path", "North-South"},               --UNDERGROUND_PATH
    [87] = {"Kanto Dungeons", "Rock Tunnel", "Rock Tunnel 1F"},                 --ROCK_TUNNEL_1F
    [88] = {"Kanto Dungeons", "Rock Tunnel", "Rock Tunnel B1F"},                --ROCK_TUNNEL_B1F
    [89] = {},                                                                  --SAFARI_ZONE_FUCHSIA_GATE_BETA [does not exist]
    [90] = {},                                                                  --SAFARI_ZONE_BETA [does not exist]
    [91] = {"Johto Dungeons", "Victory Road"},                                  --VICTORY_ROAD
    [92] = {"Kanto Dungeons", "Underground Path", "East-West"},                 --EAST_WEST_UNDERGROUND
    [93] = {"Johto Dungeons", "Flooded Mine"},                                  --FLOODED_MINE
  },
  [4] =  {
    [1] =  {"Johto Cities", "Ecruteak City", "Tin Tower Entrance Gate"}, --ECRUTEAK_TIN_TOWER_ENTRANCE
    [2] =  {"Johto Cities", "Ecruteak City", "Wise Trio's Room"},        --WISE_TRIOS_ROOM
    [3] =  {"Johto Cities", "Ecruteak City", "PokeCenter"},              --ECRUTEAK_POKECENTER_1F
    [4] =  {"Johto Cities", "Ecruteak City", "Lugia Speech House"},      --ECRUTEAK_LUGIA_SPEECH_HOUSE
    [5] =  {"Johto Cities", "Ecruteak City", "Dance Theater"},           --DANCE_THEATER
    [6] =  {"Johto Cities", "Ecruteak City", "Mart"},                    --ECRUTEAK_MART
    [7] =  {"Johto Cities", "Ecruteak City", "Gym"},                     --ECRUTEAK_GYM
    [8] =  {"Johto Cities", "Ecruteak City", "Itemfinder House"},        --ECRUTEAK_ITEMFINDER_HOUSE
    [9] =  {"Johto Cities", "Ecruteak City", "City"},                    --ECRUTEAK_CITY
  },
  [5] =  {
    [1] =  {"Johto Cities", "Blackthorn City", "Gym", "1F"},            --BLACKTHORN_GYM_1F
    [2] =  {"Johto Cities", "Blackthorn City", "Gym", "2F"},            --BLACKTHORN_GYM_2F
    [3] =  {"Johto Cities", "Blackthorn City", "Dragon Speech House"},  --BLACKTHORN_DRAGON_SPEECH_HOUSE
    [4] =  {"Johto Cities", "Blackthorn City", "Emy's House"},          --BLACKTHORN_EMYS_HOUSE
    [5] =  {"Johto Cities", "Blackthorn City", "Mart"},                 --BLACKTHORN_MART
    [6] =  {"Johto Cities", "Blackthorn City", "PokeCenter"},           --BLACKTHORN_POKECENTER_1F
    [7] =  {"Johto Cities", "Blackthorn City", "Move Deleter's House"}, --MOVE_DELETERS_HOUSE
    [8] =  {"Johto Routes", "Route 45"},                                --ROUTE_45
    [9] =  {"Johto Routes", "Route 46"},                                --ROUTE_46
    [10] = {"Johto Cities", "Blackthorn City", "City"},                 --BLACKTHORN_CITY
  },
  [6] =  {
    [1] =  {"Kanto Cities", "Cinnabar Island", "Center"}, --CINNABAR_POKECENTER_1F
    [2] =  {},                                            --CINNABAR_POKECENTER_2F_BETA [does not exist]
    [3] =  {"Kanto Routes", "Route 19", "Fuchsia Gate"},  --ROUTE_19_FUCHSIA_GATE
    [4] =  {"Kanto Routes", "Route 20", "Seafoam Gym"},   --SEAFOAM_GYM
    [5] =  {"Kanto Routes", "Route 19", "Route"},         --ROUTE_19
    [6] =  {"Kanto Routes", "Route 20", "Route"},         --ROUTE_20
    [7] =  {"Kanto Routes", "Route 21"},                  --ROUTE_21
    [8] =  {"Kanto Cities", "Cinnabar Island", "Island"}, --CINNABAR_ISLAND
  },
  [7] =  {
    [1] =  {"Kanto Cities", "Cerulean City", "Badge Speech House"}, --CERULEAN_GYM_BADGE_SPEECH_HOUSE
    [2] =  {"Kanto Cities", "Cerulean City", "Police Station"},     --CERULEAN_POLICE_STATION
    [3] =  {"Kanto Cities", "Cerulean City", "Trade Speech House"}, --CERULEAN_TRADE_SPEECH_HOUSE
    [4] =  {"Kanto Cities", "Cerulean City", "PokeCenter"},         --CERULEAN_POKECENTER_1F
    [5] =  {},                                                      --CERULEAN_POKECENTER_2F_BETA [does not exist]
    [6] =  {"Kanto Cities", "Cerulean City", "Gym"},                --CERULEAN_GYM
    [7] =  {"Kanto Cities", "Cerulean City", "Mart"},               --CERULEAN_MART
    [8] =  {"Kanto Routes", "Route 10", "PokeCenter"},              --ROUTE_10_POKECENTER_1F
    [9] =  {},                                                      --ROUTE_10_POKECENTER_2F_BETA [does not exist]
    [10] = {"Kanto Dungeons", "Power Plant"},                       --POWER_PLANT
    [11] = {"Kanto Routes", "Route 25", "Bill's House"},            --BILLS_HOUSE
    [12] = {"Kanto Routes", "Route 4"},                             --ROUTE_4
    [13] = {"Kanto Routes", "Route 9"},                             --ROUTE_9
    [14] = {"Kanto Routes", "Route 10", "Route"},                   --ROUTE_10_NORTH
    [15] = {"Kanto Routes", "Route 24"},                            --ROUTE_24
    [16] = {"Kanto Routes", "Route 25", "Route"},                   --ROUTE_25
    [17] = {"Kanto Cities", "Cerulean City", "City"},               --CERULEAN_CITY
  },
  [8] =  {
    [1] =  {"Johto Cities", "Azalea Town", "PokeCenter"},    --AZALEA_POKECENTER_1F
    [2] =  {"Johto Cities", "Azalea Town", "Charcoal Kiln"}, --CHARCOAL_KILN
    [3] =  {"Johto Cities", "Azalea Town", "Mart"},          --AZALEA_MART
    [4] =  {"Johto Cities", "Azalea Town", "Kurt's House"},  --KURTS_HOUSE
    [5] =  {"Johto Cities", "Azalea Town", "Gym"},           --AZALEA_GYM
    [6] =  {"Johto Routes", "Route 33"},                     --ROUTE_33
    [7] =  {"Johto Cities", "Azalea Town", "Town"},          --AZALEA_TOWN
  },
  [9] =  {
    [1] =  {"Johto Routes", "Lake of Rage", "Hidden Power House"}, --LAKE_OF_RAGE_HIDDEN_POWER_HOUSE
    [2] =  {"Johto Routes", "Lake of Rage", "Magikarp House"},     --LAKE_OF_RAGE_MAGIKARP_HOUSE
    [3] =  {"Johto Routes", "Route 43", "Mahogany Gate"},          --ROUTE_43_MAHOGANY_GATE
    [4] =  {"Johto Routes", "Route 43", "Scam Gate"},              --ROUTE_43_GATE
    [5] =  {"Johto Routes", "Route 43", "Route"},                  --ROUTE_43
    [6] =  {"Johto Routes", "Lake of Rage", "Outside"},            --LAKE_OF_RAGE
  },
  [10] =  {
    [1] =  {"Johto Routes", "Route 32", "Route"},                     --ROUTE_32
    [2] =  {"Johto Routes", "Route 35", "Route"},                     --ROUTE_35
    [3] =  {"Johto Routes", "Route 36", "Route"},                     --ROUTE_36
    [4] =  {"Johto Routes", "Route 37"},                              --ROUTE_37
    [5] =  {"Johto Cities", "Violet City", "City"},                   --VIOLET_CITY
    [6] =  {"Johto Cities", "Violet City", "Mart"},                   --VIOLET_MART
    [7] =  {"Johto Cities", "Violet City", "Gym"},                    --VIOLET_GYM
    [8] =  {"Johto Cities", "Violet City", "Earl's Pokemon Academy"}, --EARLS_POKEMON_ACADEMY
    [9] =  {"Johto Cities", "Violet City", "Nickname Speech House"},  --VIOLET_NICKNAME_SPEECH_HOUSE
    [10] = {"Johto Cities", "Violet City", "PokeCenter"},             --VIOLET_POKECENTER_1F
    [11] = {"Johto Cities", "Violet City", "Kyle's House"},           --VIOLET_KYLES_HOUSE
    [12] = {"Johto Routes", "Route 32", "Ruins of Alph Gate"},        --ROUTE_32_RUINS_OF_ALPH_GATE
    [13] = {"Johto Routes", "Route 32", "PokeCenter"},                --ROUTE_32_POKECENTER_1F
    [14] = {"Johto Routes", "Route 35", "Goldenrod Gate"},            --ROUTE_35_GOLDENROD_GATE
    [15] = {"Johto Routes", "Route 35", "National Park Gate"},        --ROUTE_35_NATIONAL_PARK_GATE
    [16] = {"Johto Routes", "Route 36", "Ruins of Alph Gate"},        --ROUTE_36_RUINS_OF_ALPH_GATE
    [17] = {"Johto Routes", "Route 36", "National Park Gate"},        --ROUTE_36_NATIONAL_PARK_GATE
  },
  [11] =  {
    [1] =  {"Johto Routes", "Route 34", "Route"},                                                         --ROUTE_34
    [2] =  {"Johto Cities", "Goldenrod City", "City"},                                                    --GOLDENROD_CITY
    [3] =  {"Johto Cities", "Goldenrod City", "Gym"},                                                     --GOLDENROD_GYM
    [4] =  {"Johto Cities", "Goldenrod City", "Bike Shop"},                                               --GOLDENROD_BIKE_SHOP
    [5] =  {"Johto Cities", "Goldenrod City", "Happiness Rater"},                                         --GOLDENROD_HAPPINESS_RATER
    [6] =  {"Johto Cities", "Goldenrod City", "Bill's Family's House"},                                   --BILLS_FAMILYS_HOUSE
    [7] =  {"Johto Cities", "Goldenrod City", "Magnet Train Station"},                                    --GOLDENROD_MAGNET_TRAIN_STATION
    [8] =  {"Johto Cities", "Goldenrod City", "Flower Shop"},                                             --GOLDENROD_FLOWER_SHOP
    [9] =  {"Johto Cities", "Goldenrod City", "PP Speech House (yes, yes, the birds and the bees talk)"}, --GOLDENROD_PP_SPEECH_HOUSE
    [10] = {"Johto Cities", "Goldenrod City", "Name Rater"},                                              --GOLDENROD_NAME_RATER
    [11] = {"Johto Cities", "Goldenrod City", "Dept. Store", "1F"},                                       --GOLDENROD_DEPT_STORE_1F
    [12] = {"Johto Cities", "Goldenrod City", "Dept. Store", "2F"},                                       --GOLDENROD_DEPT_STORE_2F
    [13] = {"Johto Cities", "Goldenrod City", "Dept. Store", "3F"},                                       --GOLDENROD_DEPT_STORE_3F
    [14] = {"Johto Cities", "Goldenrod City", "Dept. Store", "4F"},                                       --GOLDENROD_DEPT_STORE_4F
    [15] = {"Johto Cities", "Goldenrod City", "Dept. Store", "5F"},                                       --GOLDENROD_DEPT_STORE_5F
    [16] = {"Johto Cities", "Goldenrod City", "Dept. Store", "6F"},                                       --GOLDENROD_DEPT_STORE_6F
    [17] = {"Johto Cities", "Goldenrod City", "Dept. Store", "Elevator"},                                 --GOLDENROD_DEPT_STORE_ELEVATOR
    [18] = {"Johto Cities", "Goldenrod City", "Dept. Store", "Roof"},                                     --GOLDENROD_DEPT_STORE_ROOF
    [19] = {"Johto Cities", "Goldenrod City", "Game Corner"},                                             --GOLDENROD_GAME_CORNER
    [20] = {"Johto Cities", "Goldenrod City", "PokeCenter"},                                              --GOLDENROD_POKECENTER_1F
    [21] = {},                                                                                            --POKECOM_CENTER_ADMIN_OFFICE_MOBILE [does not exist]
    [22] = {"Johto Cities", "Azalea Town", "Ilex Forest Gate"},                                           --ILEX_FOREST_AZALEA_GATE
    [23] = {"Johto Routes", "Route 34", "Ilex Forest Gate"},                                              --ROUTE_34_ILEX_FOREST_GATE
    [24] = {"Johto Routes", "Route 34", "Day Care"},                                                      --DAY_CARE
  },
  [12] =  {

    [1] =  {"Kanto Routes", "Route 6", "Route"},                              --ROUTE_6
    [2] =  {"Kanto Routes", "Route 11"},                                      --ROUTE_11
    [3] =  {"Kanto Cities", "Vermilion City", "City"},                        --VERMILION_CITY
    [4] =  {"Kanto Cities", "Vermilion City", "Fishing Speech House"},        --VERMILION_FISHING_SPEECH_HOUSE
    [5] =  {"Kanto Cities", "Vermilion City", "PokeCenter"},                  --VERMILION_POKECENTER_1F
    [6] =  {},                                                                --VERMILION_POKECENTER_2F_BETA [does not exist]
    [7] =  {"Kanto Cities", "Vermilion City", "Pokemon Fan Club"},            --POKEMON_FAN_CLUB
    [8] =  {"Kanto Cities", "Vermilion City", "Magnet Train Speech House"},   --VERMILION_MAGNET_TRAIN_SPEECH_HOUSE
    [9] =  {"Kanto Cities", "Vermilion City", "Mart"},                        --VERMILION_MART
    [10] = {"Kanto Cities", "Vermilion City", "Diglett's Cave Speech House"}, --VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE
    [11] = {"Kanto Cities", "Vermilion City", "Gym"},                         --VERMILION_GYM
    [12] = {"Kanto Routes", "Route 6", "Saffron Gate"},                       --ROUTE_6_SAFFRON_GATE
    [13] = {"Kanto Routes", "Route 6", "Underground Path Entrance"},          --ROUTE_6_UNDERGROUND_PATH_ENTRANCE

  },
  [13] =  {
    [1] =  {"Kanto Routes", "Route 1"},                       --ROUTE_1
    [2] =  {"Kanto Cities", "Pallet Town", "Town"},           --PALLET_TOWN
    [3] =  {"Kanto Cities", "Pallet Town", "Red's House 1F"}, --REDS_HOUSE_1F
    [4] =  {"Kanto Cities", "Pallet Town", "Red's House 2F"}, --REDS_HOUSE_2F
    [5] =  {"Kanto Cities", "Pallet Town", "Blue's House"},   --BLUES_HOUSE
    [6] =  {"Kanto Cities", "Pallet Town", "Oak's Lab"},      --OAKS_LAB
  },
  [14] =  {
    [1] =  {"Kanto Routes", "Route 3"},                             --ROUTE_3
    [2] =  {"Kanto Cities", "Pewter City", "City"},                 --PEWTER_CITY
    [3] =  {"Kanto Cities", "Pewter City", "Nidoran Speech House"}, --PEWTER_NIDORAN_SPEECH_HOUSE
    [4] =  {"Kanto Cities", "Pewter City", "Gym"},                  --PEWTER_GYM
    [5] =  {"Kanto Cities", "Pewter City", "Mart"},                 --PEWTER_MART
    [6] =  {"Kanto Cities", "Pewter City", "PokeCenter"},           --PEWTER_POKECENTER_1F
    [7] =  {},                                                      --PEWTER_POKECENTER_2F_BETA [does not exist]
    [8] =  {"Kanto Cities", "Pewter City", "Snooze Speech House"},  --PEWTER_SNOOZE_SPEECH_HOUSE
  },
  [15] =  {
    [1] =  {"S.S. Aqua", "Olivine Port"},                          --OLIVINE_PORT
    [2] =  {"S.S. Aqua", "Vermilion Port"},                        --VERMILION_PORT
    [3] =  {},                                                     --FAST_SHIP_1F [ignore: special handling in archipelago.lua]
    [4] =  {},                                                     --FAST_SHIP_CABINS_NNW_NNE_NE [ignore: special handling in archipelago.lua]
    [5] =  {},                                                     --FAST_SHIP_CABINS_SW_SSW_NW [ignore: special handling in archipelago.lua]
    [6] =  {},                                                     --FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN [ignore: special handling in archipelago.lua]
    [7] =  {},                                                     --FAST_SHIP_B1F [ignore: special handling in archipelago.lua]
    [8] =  {"Johto Cities", "Olivine City", "Port Passage"},       --OLIVINE_PORT_PASSAGE
    [9] =  {"Kanto Cities", "Vermilion City", "Port Passage"},     --VERMILION_PORT_PASSAGE
    [10] = {"Kanto Dungeons", "Mount Moon", "Square"},             --MOUNT_MOON_SQUARE
    [11] = {"Kanto Dungeons", "Mount Moon", "Gift Shop"},          --MOUNT_MOON_GIFT_SHOP
    [12] = {"Johto Cities", "Ecruteak City", "Tin Tower", "Roof"}, --TIN_TOWER_ROOF
  },
  [115] =  {
    [1] =  {"S.S. Aqua", "Olivine Port"},                          --OLIVINE_PORT
    [2] =  {"S.S. Aqua", "Vermilion Port"},                        --VERMILION_PORT
    [3] =  {"S.S. Aqua", "Eastbound", "1F Hallways"},              --FAST_SHIP_1F
    [4] =  {"S.S. Aqua", "Eastbound", "1F Cabins"},                --FAST_SHIP_CABINS_NNW_NNE_NE
    [5] =  {"S.S. Aqua", "Eastbound", "1F Cabins"},                --FAST_SHIP_CABINS_SW_SSW_NW
    [6] =  {"S.S. Aqua", "Eastbound", "1F Cabins"},                --FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN
    [7] =  {"S.S. Aqua", "Eastbound", "B1F"},                      --FAST_SHIP_B1F
    [8] =  {"Johto Cities", "Olivine City", "Port Passage"},       --OLIVINE_PORT_PASSAGE
    [9] =  {"Kanto Cities", "Vermilion City", "Port Passage"},     --VERMILION_PORT_PASSAGE
    [10] = {"Kanto Dungeons", "Mount Moon", "Square"},             --MOUNT_MOON_SQUARE
    [11] = {"Kanto Dungeons", "Mount Moon", "Gift Shop"},          --MOUNT_MOON_GIFT_SHOP
    [12] = {"Johto Cities", "Ecruteak City", "Tin Tower", "Roof"}, --TIN_TOWER_ROOF
  },
  [215] =  {
    [1] =  {"S.S. Aqua", "Olivine Port"},                          --OLIVINE_PORT
    [2] =  {"S.S. Aqua", "Vermilion Port"},                        --VERMILION_PORT
    [3] =  {"S.S. Aqua", "Westbound", "1F Hallways"},              --FAST_SHIP_1F
    [4] =  {"S.S. Aqua", "Westbound", "1F Cabins"},                --FAST_SHIP_CABINS_NNW_NNE_NE
    [5] =  {"S.S. Aqua", "Westbound", "1F Cabins"},                --FAST_SHIP_CABINS_SW_SSW_NW
    [6] =  {"S.S. Aqua", "Westbound", "1F Cabins"},                --FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN
    [7] =  {"S.S. Aqua", "Westbound", "B1F"},                      --FAST_SHIP_B1F
    [8] =  {"Johto Cities", "Olivine City", "Port Passage"},       --OLIVINE_PORT_PASSAGE
    [9] =  {"Kanto Cities", "Vermilion City", "Port Passage"},     --VERMILION_PORT_PASSAGE
    [10] = {"Kanto Dungeons", "Mount Moon", "Square"},             --MOUNT_MOON_SQUARE
    [11] = {"Kanto Dungeons", "Mount Moon", "Gift Shop"},          --MOUNT_MOON_GIFT_SHOP
    [12] = {"Johto Cities", "Ecruteak City", "Tin Tower", "Roof"}, --TIN_TOWER_ROOF
  },
  [16] =  {
    [1] =  {"Johto Routes", "Route 23", "Vanilla"},            --ROUTE_23 [vanilla]
    [2] =  {"Johto Cities", "Indigo Plateau", "PokeCenter"},   --INDIGO_PLATEAU_POKECENTER_1F
    [3] =  {"Johto Cities", "Indigo Plateau", "Will's Room"},  --WILLS_ROOM
    [4] =  {"Johto Cities", "Indigo Plateau", "Koga's Room"},  --KOGAS_ROOM
    [5] =  {"Johto Cities", "Indigo Plateau", "Bruno's Room"}, --BRUNOS_ROOM
    [6] =  {"Johto Cities", "Indigo Plateau", "Karen's Room"}, --KARENS_ROOM
    [7] =  {"Johto Cities", "Indigo Plateau", "Lance's Room"}, --LANCES_ROOM
    [8] =  {"Johto Cities", "Indigo Plateau", "Hall of Fame"}, --HALL_OF_FAME
    [9] =  {"Johto Routes", "Route 23", "Restored"},           --ROUTE_23 [restored]
  },
  [17] =  {
    [1] =  {"Kanto Routes", "Route 13"},                                   --ROUTE_13
    [2] =  {"Kanto Routes", "Route 14"},                                   --ROUTE_14
    [3] =  {"Kanto Routes", "Route 15", "Route"},                          --ROUTE_15
    [4] =  {"Kanto Routes", "Route 18"},                                   --ROUTE_18
    [5] =  {"Kanto Cities", "Fuchsia City", "City"},                       --FUCHSIA_CITY
    [6] =  {"Kanto Cities", "Fuchsia City", "Mart"},                       --FUCHSIA_MART
    [7] =  {"Kanto Cities", "Fuchsia City", "Safari Zone Main Office"},    --SAFARI_ZONE_MAIN_OFFICE
    [8] =  {"Kanto Cities", "Fuchsia City", "Gym"},                        --FUCHSIA_GYM
    [9] =  {"Kanto Cities", "Fuchsia City", "Bill's Brother's House"},     --BILLS_BROTHERS_HOUSE
    [10] = {"Kanto Cities", "Fuchsia City", "PokeCenter"},                 --FUCHSIA_POKECENTER_1F
    [11] = {},                                                             --FUCHSIA_POKECENTER_2F_BETA [does not exist]
    [12] = {"Kanto Cities", "Fuchsia City", "Safari Zone Warden's House"}, --SAFARI_ZONE_WARDENS_HOME
    [13] = {"Kanto Routes", "Route 15", "Fuchsia Gate"},                   --ROUTE_15_FUCHSIA_GATE
  },
  [18] =  {
    [1] =  {"Kanto Routes", "Route 8", "Route"},                       --ROUTE_8
    [2] =  {"Kanto Routes", "Route 12", "Route"},                      --ROUTE_12
    [3] =  {"Kanto Routes", "Route 10", "Route"},                      --ROUTE_10_SOUTH
    [4] =  {"Kanto Cities", "Lavender Town", "Town"},                  --LAVENDER_TOWN
    [5] =  {"Kanto Cities", "Lavender Town", "PokeCenter"},            --LAVENDER_POKECENTER_1F
    [6] =  {},                                                         --LAVENDER_POKECENTER_2F_BETA [does not exist]
    [7] =  {"Kanto Cities", "Lavender Town", "Mr. Fuji's House"},      --MR_FUJIS_HOUSE
    [8] =  {"Kanto Cities", "Lavender Town", "Lavender Speech House"}, --LAVENDER_SPEECH_HOUSE
    [9] =  {"Kanto Cities", "Lavender Town", "Name Rater"},            --LAVENDER_NAME_RATER
    [10] = {"Kanto Cities", "Lavender Town", "Mart"},                  --LAVENDER_MART
    [11] = {"Kanto Cities", "Lavender Town", "Soul House"},            --SOUL_HOUSE
    [12] = {"Kanto Cities", "Lavender Town", "Radio Tower"},           --LAV_RADIO_TOWER_1F
    [13] = {"Kanto Routes", "Route 8", "Saffron Gate"},                --ROUTE_8_SAFFRON_GATE
    [14] = {"Kanto Routes", "Route 12", "Super Rod House"},            --ROUTE_12_SUPER_ROD_HOUSE
  },
  [19] =  {
    [1] =  {"Johto Routes", "Route 28", "Route"},               --ROUTE_28
    [2] =  {"Johto Routes", "Route 28", "Outside Silver Cave"}, --SILVER_CAVE_OUTSIDE
    [3] =  {"Johto Routes", "Route 28", "PokeCenter"},          --SILVER_CAVE_POKECENTER_1F
    [4] =  {"Johto Routes", "Route 28", "Steel Wing House"},    --ROUTE_28_STEEL_WING_HOUSE
  },
  [20] =  {
    [1] =  {}, --POKECENTER_2F
    [2] =  {}, --TRADE_CENTER
    [3] =  {}, --COLOSSEUM
    [4] =  {}, --TIME_CAPSULE
    [5] =  {}, --MOBILE_TRADE_ROOM
    [6] =  {}, --MOBILE_BATTLE_ROOM
  },
  [21] =  {
    [1] =  {"Kanto Routes", "Route 7", "Route"},                        --ROUTE_7
    [2] =  {"Kanto Routes", "Route 16", "Route"},                       --ROUTE_16
    [3] =  {"Kanto Routes", "Route 17", "Route"},                       --ROUTE_17
    [4] =  {"Kanto Cities", "Celadon City", "City"},                    --CELADON_CITY
    [5] =  {"Kanto Cities", "Celadon City", "Dept. Store", "1F"},       --CELADON_DEPT_STORE_1F
    [6] =  {"Kanto Cities", "Celadon City", "Dept. Store", "2F"},       --CELADON_DEPT_STORE_2F
    [7] =  {"Kanto Cities", "Celadon City", "Dept. Store", "3F"},       --CELADON_DEPT_STORE_3F
    [8] =  {"Kanto Cities", "Celadon City", "Dept. Store", "4F"},       --CELADON_DEPT_STORE_4F
    [9] =  {"Kanto Cities", "Celadon City", "Dept. Store", "5F"},       --CELADON_DEPT_STORE_5F
    [10] = {"Kanto Cities", "Celadon City", "Dept. Store", "6F"},       --CELADON_DEPT_STORE_6F
    [11] = {"Kanto Cities", "Celadon City", "Dept. Store", "Elevator"}, --CELADON_DEPT_STORE_ELEVATOR
    [12] = {"Kanto Cities", "Celadon City", "Mansion", "1F"},           --CELADON_MANSION_1F
    [13] = {"Kanto Cities", "Celadon City", "Mansion", "2F"},           --CELADON_MANSION_2F
    [14] = {"Kanto Cities", "Celadon City", "Mansion", "3F"},           --CELADON_MANSION_3F
    [15] = {"Kanto Cities", "Celadon City", "Mansion", "Roof"},         --CELADON_MANSION_ROOF
    [16] = {"Kanto Cities", "Celadon City", "Mansion", "Penthouse"},    --CELADON_MANSION_ROOF_HOUSE
    [17] = {"Kanto Cities", "Celadon City", "PokeCenter"},              --CELADON_POKECENTER_1F
    [18] = {},                                                          --CELADON_POKECENTER_2F_BETA [does not exist]
    [19] = {"Kanto Cities", "Celadon City", "Game Corner"},             --CELADON_GAME_CORNER
    [20] = {"Kanto Cities", "Celadon City", "Game Corner Prize Room"},  --CELADON_GAME_CORNER_PRIZE_ROOM
    [21] = {"Kanto Cities", "Celadon City", "Gym"},                     --CELADON_GYM
    [22] = {"Kanto Cities", "Celadon City", "Cafe"},                    --CELADON_CAFE
    [23] = {"Kanto Routes", "Route 16", "Fuchsia Speech House"},        --ROUTE_16_FUCHSIA_SPEECH_HOUSE
    [24] = {"Kanto Routes", "Route 16", "Gate"},                        --ROUTE_16_GATE
    [25] = {"Kanto Routes", "Route 7", "Saffron Gate"},                 --ROUTE_7_SAFFRON_GATE
    [26] = {"Kanto Routes", "Route 17", "Route 18 Gate"},               --ROUTE_17_ROUTE_18_GATE
  },
  [22] =  {
    [1] =  {"Johto Routes", "Route 40"},                            --ROUTE_40
    [2] =  {"Johto Routes", "Route 41"},                            --ROUTE_41
    [3] =  {"Johto Cities", "Cianwood City", "City"},               --CIANWOOD_CITY
    [4] =  {"Johto Cities", "Cianwood City", "Mania's House"},      --MANIAS_HOUSE
    [5] =  {"Johto Cities", "Cianwood City", "Gym"},                --CIANWOOD_GYM
    [6] =  {"Johto Cities", "Cianwood City", "PokeCenter"},         --CIANWOOD_POKECENTER_1F
    [7] =  {"Johto Cities", "Cianwood City", "Pharmacy"},           --CIANWOOD_PHARMACY
    [8] =  {"Johto Cities", "Cianwood City", "Photo Studio"},       --CIANWOOD_PHOTO_STUDIO
    [9] =  {"Johto Cities", "Cianwood City", "Lugia Speech House"}, --CIANWOOD_LUGIA_SPEECH_HOUSE
    [10] = {"Johto Cities", "Cianwood City", "PokeSeer's House"},   --POKE_SEERS_HOUSE
    [11] = {"Johto Dungeons", "Battle Tower", "1F"},                --BATTLE_TOWER_1F
    [12] = {},                                                      --BATTLE_TOWER_BATTLE_ROOM
    [13] = {},                                                      --BATTLE_TOWER_ELEVATOR
    [14] = {},                                                      --BATTLE_TOWER_HALLWAY
    [15] = {"Johto Dungeons", "Battle Tower", "Gate"},              --ROUTE_40_BATTLE_TOWER_GATE
    [16] = {"Johto Dungeons", "Battle Tower", "Outside"},           --BATTLE_TOWER_OUTSIDE
  },
  [23] =  {
    [1] =  {"Kanto Routes", "Route 2", "Route"},                       --ROUTE_2
    [2] =  {"Kanto Routes", "Route 22"},                               --ROUTE_22
    [3] =  {"Kanto Cities", "Viridian City", "City"},                  --VIRIDIAN_CITY
    [4] =  {"Kanto Cities", "Viridian City", "Gym"},                   --VIRIDIAN_GYM
    [5] =  {"Kanto Cities", "Viridian City", "Nickname Speech House"}, --VIRIDIAN_NICKNAME_SPEECH_HOUSE
    [6] =  {"Kanto Cities", "Viridian City", "Trainer House 1F"},      --TRAINER_HOUSE_1F
    [7] =  {"Kanto Cities", "Viridian City", "Trainer House B1F"},     --TRAINER_HOUSE_B1F
    [8] =  {"Kanto Cities", "Viridian City", "Mart"},                  --VIRIDIAN_MART
    [9] =  {"Kanto Cities", "Viridian City", "PokeCenter"},            --VIRIDIAN_POKECENTER_1F
    [10] = {},                                                         --VIRIDIAN_POKECENTER_2F_BETA [does not exist]
    [11] = {"Kanto Routes", "Route 2", "Nugget House"},                --ROUTE_2_NUGGET_HOUSE
    [12] = {"Kanto Routes", "Route 2", "Gate"},                        --ROUTE_2_GATE
    [13] = {"Johto Routes", "Victory Road Gate"},                      --VICTORY_ROAD_GATE
  },
  [24] =  {
    [1] =  {"Johto Routes", "Route 26", "Route"},                       --ROUTE_26
    [2] =  {"Johto Routes", "Route 27", "Route"},                       --ROUTE_27
    [3] =  {"Johto Routes", "Route 29", "Route"},                       --ROUTE_29
    [4] =  {"Johto Cities", "New Bark Town", "Town"},                   --NEW_BARK_TOWN
    [5] =  {"Johto Cities", "New Bark Town", "Elm's Lab"},              --ELMS_LAB
    [6] =  {"Johto Cities", "New Bark Town", "Player's House 1F"},      --PLAYERS_HOUSE_1F
    [7] =  {"Johto Cities", "New Bark Town", "Player's House 2F"},      --PLAYERS_HOUSE_2F
    [8] =  {"Johto Cities", "New Bark Town", "Neighbor's House"},       --PLAYERS_NEIGHBORS_HOUSE
    [9] =  {"Johto Cities", "New Bark Town", "Elm's House"},            --ELMS_HOUSE
    [10] = {"Johto Routes", "Route 26", "Heal House"},                  --ROUTE_26_HEAL_HOUSE
    [11] = {"Johto Routes", "Route 26", "Day of Week Sibling's House"}, --DAY_OF_WEEK_SIBLINGS_HOUSE
    [12] = {"Johto Routes", "Route 27", "Sandstorm House"},             --ROUTE_27_SANDSTORM_HOUSE
    [13] = {"Johto Routes", "Route 29", "Route 46 Gate"},               --ROUTE_29_ROUTE_46_GATE
  },
  [25] =  {
    [1] =  {"Kanto Routes", "Route 5", "Route"},                     --ROUTE_5
    [2] =  {"Kanto Cities", "Saffron City", "City"},                 --SAFFRON_CITY
    [3] =  {"Kanto Cities", "Saffron City", "Fighting Dojo"},        --FIGHTING_DOJO
    [4] =  {"Kanto Cities", "Saffron City", "Gym"},                  --SAFFRON_GYM
    [5] =  {"Kanto Cities", "Saffron City", "Mart"},                 --SAFFRON_MART
    [6] =  {"Kanto Cities", "Saffron City", "PokeCenter"},           --SAFFRON_POKECENTER_1F
    [7] =  {},                                                       --SAFFRON_POKECENTER_2F_BETA [does not exist]
    [8] =  {"Kanto Cities", "Saffron City", "Mr. Psychic's House"},  --MR_PSYCHICS_HOUSE
    [9] =  {"Kanto Cities", "Saffron City", "Magnet Train Station"}, --SAFFRON_MAGNET_TRAIN_STATION
    [10] = {"Kanto Cities", "Saffron City", "Silph Co"},             --SILPH_CO_1F
    [11] = {"Kanto Cities", "Saffron City", "Copycat's House 1F"},   --COPYCATS_HOUSE_1F
    [12] = {"Kanto Cities", "Saffron City", "Copycat's House 2F"},   --COPYCATS_HOUSE_2F
    [13] = {"Kanto Routes", "Route 5", "Underground Path Entrance"}, --ROUTE_5_UNDERGROUND_PATH_ENTRANCE
    [14] = {"Kanto Routes", "Route 5", "Saffron Gate"},              --ROUTE_5_SAFFRON_GATE
    [15] = {"Kanto Routes", "Route 5", "Cleanse Tag House"},         --ROUTE_5_CLEANSE_TAG_HOUSE
    [16] = {"Kanto Routes", "Route 7", "Underground Path Entrance"}, --ROUTE_5_UNDERGROUND_PATH_ENTRANCE
    [17] = {"Kanto Routes", "Route 8", "Underground Path Entrance"}, --ROUTE_5_UNDERGROUND_PATH_ENTRANCE
  },
  [26] =  {
    [1] =  {"Johto Routes", "Route 30", "Route"},                          --ROUTE_30
    [2] =  {"Johto Routes", "Route 31", "Route"},                          --ROUTE_31
    [3] =  {"Johto Cities", "Cherrygrove City", "City"},                   --CHERRYGROVE_CITY
    [4] =  {"Johto Cities", "Cherrygrove City", "Mart"},                   --CHERRYGROVE_MART
    [5] =  {"Johto Cities", "Cherrygrove City", "PokeCenter"},             --CHERRYGROVE_POKECENTER_1F
    [6] =  {"Johto Cities", "Cherrygrove City", "Gym Speech House"},       --CHERRYGROVE_GYM_SPEECH_HOUSE
    [7] =  {"Johto Cities", "Cherrygrove City", "Guide Gent's House"},     --GUIDE_GENTS_HOUSE
    [8] =  {"Johto Cities", "Cherrygrove City", "Evolution Speech House"}, --CHERRYGROVE_EVOLUTION_SPEECH_HOUSE
    [9] =  {"Johto Routes", "Route 30", "Berry House"},                    --ROUTE_30_BERRY_HOUSE
    [10] = {"Johto Routes", "Route 30", "Mr. Pokémon's House"},            --MR_POKEMONS_HOUSE
    [11] = {"Johto Routes", "Route 31", "Violet Gate"},                    --ROUTE_31_VIOLET_GATE
  }
}
