-- Fly-destination data, generated from the apworld (data/entrance_data.json + data/data.json).
-- Loaded before connections.lua and read by archipelago.lua's onClear.
--
-- FLY_ARRIVAL_REGIONS: "<CamelCaseMap>:<warp_index>" -> destination region a fly to that
--   overworld warp lands you in. Keys are exactly the [map_name, warp_index] pairs the
--   apworld sends in slot_data.fly_destinations. Matches regions.py _get_fly_dest_region:
--   entrance_region of the connection whose arrival_map/arrival_warp_id equal the flypoint.
--   (Route23Restored's two arrivals are synthesized at apworld runtime, appended here.)

FLY_ARRIVAL_REGIONS = {
    ["AzaleaTown:1"] = "REGION_AZALEA_TOWN",
    ["AzaleaTown:2"] = "REGION_AZALEA_TOWN",
    ["AzaleaTown:3"] = "REGION_AZALEA_TOWN",
    ["AzaleaTown:4"] = "REGION_AZALEA_TOWN",
    ["AzaleaTown:5"] = "REGION_AZALEA_TOWN",
    ["AzaleaTown:6"] = "REGION_AZALEA_TOWN:WELL",
    ["AzaleaTown:7"] = "REGION_AZALEA_TOWN",
    ["BattleTowerOutside:1"] = "REGION_BATTLE_TOWER_OUTSIDE",
    ["BattleTowerOutside:3"] = "REGION_BATTLE_TOWER_OUTSIDE",
    ["BlackthornCity:1"] = "REGION_BLACKTHORN_CITY",
    ["BlackthornCity:2"] = "REGION_BLACKTHORN_CITY",
    ["BlackthornCity:3"] = "REGION_BLACKTHORN_CITY",
    ["BlackthornCity:4"] = "REGION_BLACKTHORN_CITY",
    ["BlackthornCity:5"] = "REGION_BLACKTHORN_CITY",
    ["BlackthornCity:6"] = "REGION_BLACKTHORN_CITY",
    ["BlackthornCity:7"] = "REGION_BLACKTHORN_CITY",
    ["BlackthornCity:8"] = "REGION_BLACKTHORN_CITY:DRAGONS_DEN_ENTRANCE",
    ["CeladonCity:1"] = "REGION_CELADON_CITY",
    ["CeladonCity:2"] = "REGION_CELADON_CITY",
    ["CeladonCity:3"] = "REGION_CELADON_CITY",
    ["CeladonCity:5"] = "REGION_CELADON_CITY",
    ["CeladonCity:6"] = "REGION_CELADON_CITY",
    ["CeladonCity:7"] = "REGION_CELADON_CITY",
    ["CeladonCity:8"] = "REGION_CELADON_CITY:GYM_ENTRANCE",
    ["CeladonCity:9"] = "REGION_CELADON_CITY",
    ["CeruleanCity:1"] = "REGION_CERULEAN_CITY",
    ["CeruleanCity:2"] = "REGION_CERULEAN_CITY",
    ["CeruleanCity:3"] = "REGION_CERULEAN_CITY",
    ["CeruleanCity:4"] = "REGION_CERULEAN_CITY",
    ["CeruleanCity:5"] = "REGION_CERULEAN_CITY",
    ["CeruleanCity:6"] = "REGION_CERULEAN_CITY",
    ["CherrygroveCity:1"] = "REGION_CHERRYGROVE_CITY",
    ["CherrygroveCity:2"] = "REGION_CHERRYGROVE_CITY",
    ["CherrygroveCity:3"] = "REGION_CHERRYGROVE_CITY",
    ["CherrygroveCity:4"] = "REGION_CHERRYGROVE_CITY",
    ["CherrygroveCity:5"] = "REGION_CHERRYGROVE_CITY",
    ["CherrygroveCity:6"] = "REGION_CHERRYGROVE_CITY:FLOODED_MINE_ENTRANCE",
    ["CianwoodCity:1"] = "REGION_CIANWOOD_CITY",
    ["CianwoodCity:2"] = "REGION_CIANWOOD_CITY",
    ["CianwoodCity:3"] = "REGION_CIANWOOD_CITY",
    ["CianwoodCity:4"] = "REGION_CIANWOOD_CITY",
    ["CianwoodCity:5"] = "REGION_CIANWOOD_CITY",
    ["CianwoodCity:6"] = "REGION_CIANWOOD_CITY",
    ["CianwoodCity:7"] = "REGION_CIANWOOD_CITY",
    ["CinnabarIsland:1"] = "REGION_CINNABAR_ISLAND",
    ["EcruteakCity:1"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:3"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:4"] = "REGION_ECRUTEAK_CITY:TIN_TOWER_TRAIL",
    ["EcruteakCity:6"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:7"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:8"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:9"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:10"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:11"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:12"] = "REGION_ECRUTEAK_CITY:TIN_TOWER_TRAIL",
    ["EcruteakCity:13"] = "REGION_ECRUTEAK_CITY",
    ["EcruteakCity:14"] = "REGION_ECRUTEAK_CITY",
    ["FuchsiaCity:1"] = "REGION_FUCHSIA_CITY:CUT",
    ["FuchsiaCity:2"] = "REGION_FUCHSIA_CITY",
    ["FuchsiaCity:3"] = "REGION_FUCHSIA_CITY",
    ["FuchsiaCity:4"] = "REGION_FUCHSIA_CITY",
    ["FuchsiaCity:5"] = "REGION_FUCHSIA_CITY",
    ["FuchsiaCity:6"] = "REGION_FUCHSIA_CITY",
    ["FuchsiaCity:8"] = "REGION_FUCHSIA_CITY",
    ["FuchsiaCity:10"] = "REGION_FUCHSIA_CITY",
    ["GoldenrodCity:1"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:2"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:3"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:4"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:5"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:6"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:7"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:8"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:9"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:10"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:11"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:12"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:13"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:14"] = "REGION_GOLDENROD_CITY",
    ["GoldenrodCity:15"] = "REGION_GOLDENROD_CITY",
    ["LakeOfRage:1"] = "REGION_LAKE_OF_RAGE:HIDDEN_POWER_HOUSE",
    ["LakeOfRage:2"] = "REGION_LAKE_OF_RAGE",
    ["LavenderTown:1"] = "REGION_LAVENDER_TOWN",
    ["LavenderTown:2"] = "REGION_LAVENDER_TOWN",
    ["LavenderTown:3"] = "REGION_LAVENDER_TOWN",
    ["LavenderTown:4"] = "REGION_LAVENDER_TOWN",
    ["LavenderTown:5"] = "REGION_LAVENDER_TOWN",
    ["LavenderTown:6"] = "REGION_LAVENDER_TOWN",
    ["LavenderTown:7"] = "REGION_LAVENDER_TOWN",
    ["MahoganyTown:1"] = "REGION_MAHOGANY_TOWN",
    ["MahoganyTown:2"] = "REGION_MAHOGANY_TOWN:EAST",
    ["MahoganyTown:3"] = "REGION_MAHOGANY_TOWN",
    ["MahoganyTown:4"] = "REGION_MAHOGANY_TOWN",
    ["MahoganyTown:5"] = "REGION_MAHOGANY_TOWN",
    ["MountMoonSquare:1"] = "REGION_MOUNT_MOON_SQUARE",
    ["MountMoonSquare:2"] = "REGION_MOUNT_MOON_SQUARE",
    ["MountMoonSquare:3"] = "REGION_MOUNT_MOON_SQUARE",
    ["NewBarkTown:1"] = "REGION_NEW_BARK_TOWN",
    ["NewBarkTown:2"] = "REGION_NEW_BARK_TOWN",
    ["NewBarkTown:3"] = "REGION_NEW_BARK_TOWN",
    ["NewBarkTown:4"] = "REGION_NEW_BARK_TOWN",
    ["OlivineCity:1"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:2"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:3"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:4"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:5"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:6"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:7"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:8"] = "REGION_OLIVINE_CITY",
    ["OlivineCity:9"] = "REGION_OLIVINE_CITY",
    ["OlivinePort:1"] = "REGION_OLIVINE_PORT",
    ["PalletTown:1"] = "REGION_PALLET_TOWN",
    ["PalletTown:2"] = "REGION_PALLET_TOWN",
    ["PalletTown:3"] = "REGION_PALLET_TOWN",
    ["PewterCity:1"] = "REGION_PEWTER_CITY",
    ["PewterCity:2"] = "REGION_PEWTER_CITY",
    ["PewterCity:3"] = "REGION_PEWTER_CITY",
    ["PewterCity:4"] = "REGION_PEWTER_CITY",
    ["PewterCity:5"] = "REGION_PEWTER_CITY",
    ["Route10North:1"] = "REGION_ROUTE_10_NORTH:POKECENTER",
    ["Route10North:2"] = "REGION_ROUTE_10_NORTH:SURF",
    ["Route10South:1"] = "REGION_ROUTE_10_SOUTH",
    ["Route12:1"] = "REGION_ROUTE_12:SOUTH",
    ["Route15:1"] = "REGION_ROUTE_15",
    ["Route16:1"] = "REGION_ROUTE_16:NORTH",
    ["Route16:2"] = "REGION_ROUTE_16",
    ["Route16:4"] = "REGION_ROUTE_16:CYCLING_ROAD",
    ["Route17:1"] = "REGION_ROUTE_17",
    ["Route18:1"] = "REGION_ROUTE_18",
    ["Route19:1"] = "REGION_ROUTE_19:GATE_ENTRANCE",
    ["Route2:1"] = "REGION_ROUTE_2:NORTHEAST",
    ["Route2:2"] = "REGION_ROUTE_2:SOUTHEAST",
    ["Route2:3"] = "REGION_ROUTE_2:CENTEREAST",
    ["Route2:5"] = "REGION_ROUTE_2:NORTHEAST",
    ["Route20:1"] = "REGION_ROUTE_20:SEAFOAM",
    ["Route22:1"] = "REGION_ROUTE_22",
    ["Route23:1"] = "REGION_ROUTE_23",
    ["Route23:3"] = "REGION_ROUTE_23",
    ["Route23Restored:1"] = "REGION_ROUTE_23_RESTORED:NORTH",
    ["Route23Restored:2"] = "REGION_ROUTE_23_RESTORED:SOUTH",
    ["Route25:1"] = "REGION_ROUTE_25",
    ["Route26:1"] = "REGION_ROUTE_26",
    ["Route26:2"] = "REGION_ROUTE_26",
    ["Route26:3"] = "REGION_ROUTE_26",
    ["Route27:1"] = "REGION_ROUTE_27:CENTER",
    ["Route27:2"] = "REGION_ROUTE_27:WEST",
    ["Route27:3"] = "REGION_ROUTE_27:CENTER",
    ["Route28:1"] = "REGION_ROUTE_28:CUT",
    ["Route28:2"] = "REGION_ROUTE_28",
    ["Route29:1"] = "REGION_ROUTE_29",
    ["Route3:1"] = "REGION_ROUTE_3",
    ["Route30:1"] = "REGION_ROUTE_30",
    ["Route30:2"] = "REGION_ROUTE_30",
    ["Route31:1"] = "REGION_ROUTE_31",
    ["Route31:3"] = "REGION_ROUTE_31",
    ["Route32:1"] = "REGION_ROUTE_32:SOUTH",
    ["Route32:2"] = "REGION_ROUTE_32:NORTH",
    ["Route32:4"] = "REGION_ROUTE_32:SOUTH",
    ["Route32:5"] = "REGION_ROUTE_32:SOUTH",
    ["Route33:1"] = "REGION_ROUTE_33",
    ["Route34:1"] = "REGION_ROUTE_34",
    ["Route34:3"] = "REGION_ROUTE_34",
    ["Route34:5"] = "REGION_ROUTE_34:DAY_CARE_YARD",
    ["Route35:1"] = "REGION_ROUTE_35",
    ["Route35:3"] = "REGION_ROUTE_35",
    ["Route36:1"] = "REGION_ROUTE_36:WEST",
    ["Route36:3"] = "REGION_ROUTE_36:EAST",
    ["Route38:1"] = "REGION_ROUTE_38",
    ["Route39:1"] = "REGION_ROUTE_39",
    ["Route39:2"] = "REGION_ROUTE_39",
    ["Route4:1"] = "REGION_ROUTE_4:WEST",
    ["Route40:1"] = "REGION_ROUTE_40",
    ["Route41:1"] = "REGION_ROUTE_41:NW_ISLAND",
    ["Route41:2"] = "REGION_ROUTE_41:NE_ISLAND",
    ["Route41:3"] = "REGION_ROUTE_41:SW_ISLAND",
    ["Route41:4"] = "REGION_ROUTE_41:SE_ISLAND",
    ["Route42:1"] = "REGION_ROUTE_42:WEST",
    ["Route42:3"] = "REGION_ROUTE_42:WEST",
    ["Route42:4"] = "REGION_ROUTE_42:CENTER",
    ["Route42:5"] = "REGION_ROUTE_42:EAST",
    ["Route43:1"] = "REGION_ROUTE_43",
    ["Route43:3"] = "REGION_ROUTE_43",
    ["Route43:4"] = "REGION_ROUTE_43",
    ["Route44:1"] = "REGION_ROUTE_44",
    ["Route45:1"] = "REGION_ROUTE_45",
    ["Route46:1"] = "REGION_ROUTE_46:SOUTH",
    ["Route46:3"] = "REGION_ROUTE_46:NORTH",
    ["Route5:1"] = "REGION_ROUTE_5",
    ["Route5:2"] = "REGION_ROUTE_5",
    ["Route5:4"] = "REGION_ROUTE_5",
    ["Route6:1"] = "REGION_ROUTE_6",
    ["Route6:2"] = "REGION_ROUTE_6",
    ["Route7:1"] = "REGION_ROUTE_7",
    ["Route7:3"] = "REGION_ROUTE_7",
    ["Route8:1"] = "REGION_ROUTE_8",
    ["Route8:3"] = "REGION_ROUTE_8",
    ["Route9:1"] = "REGION_ROUTE_9",
    ["RuinsOfAlphOutside:1"] = "REGION_RUINS_OF_ALPH_OUTSIDE:WEST",
    ["RuinsOfAlphOutside:2"] = "REGION_RUINS_OF_ALPH_OUTSIDE",
    ["RuinsOfAlphOutside:3"] = "REGION_RUINS_OF_ALPH_OUTSIDE:SOUTH:OMANYTE_LEDGE",
    ["RuinsOfAlphOutside:4"] = "REGION_RUINS_OF_ALPH_OUTSIDE:SOUTH",
    ["RuinsOfAlphOutside:5"] = "REGION_RUINS_OF_ALPH_OUTSIDE",
    ["RuinsOfAlphOutside:6"] = "REGION_RUINS_OF_ALPH_OUTSIDE",
    ["RuinsOfAlphOutside:7"] = "REGION_RUINS_OF_ALPH_OUTSIDE:WEST",
    ["RuinsOfAlphOutside:8"] = "REGION_RUINS_OF_ALPH_OUTSIDE:SOUTH:UNION_LEDGE",
    ["RuinsOfAlphOutside:9"] = "REGION_RUINS_OF_ALPH_OUTSIDE",
    ["RuinsOfAlphOutside:10"] = "REGION_RUINS_OF_ALPH_OUTSIDE",
    ["SaffronCity:1"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:2"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:3"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:4"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:5"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:6"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:7"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:8"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:9"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:10"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:12"] = "REGION_SAFFRON_CITY",
    ["SaffronCity:14"] = "REGION_SAFFRON_CITY",
    ["SilverCaveOutside:1"] = "REGION_SILVER_CAVE_OUTSIDE",
    ["SilverCaveOutside:2"] = "REGION_SILVER_CAVE_OUTSIDE",
    ["TinTowerRoof:1"] = "REGION_TIN_TOWER_ROOF",
    ["VermilionCity:1"] = "REGION_VERMILION_CITY",
    ["VermilionCity:2"] = "REGION_VERMILION_CITY",
    ["VermilionCity:3"] = "REGION_VERMILION_CITY",
    ["VermilionCity:4"] = "REGION_VERMILION_CITY",
    ["VermilionCity:5"] = "REGION_VERMILION_CITY",
    ["VermilionCity:6"] = "REGION_VERMILION_CITY",
    ["VermilionCity:7"] = "REGION_VERMILION_CITY:GYM_ENTRANCE",
    ["VermilionCity:8"] = "REGION_VERMILION_CITY",
    ["VermilionCity:10"] = "REGION_VERMILION_CITY:DIGLETTS_CAVE_ENTRANCE",
    ["VermilionPort:1"] = "REGION_VERMILION_PORT",
    ["VioletCity:1"] = "REGION_VIOLET_CITY",
    ["VioletCity:2"] = "REGION_VIOLET_CITY",
    ["VioletCity:3"] = "REGION_VIOLET_CITY",
    ["VioletCity:4"] = "REGION_VIOLET_CITY",
    ["VioletCity:5"] = "REGION_VIOLET_CITY",
    ["VioletCity:6"] = "REGION_VIOLET_CITY",
    ["VioletCity:7"] = "REGION_VIOLET_CITY",
    ["VioletCity:8"] = "REGION_VIOLET_CITY",
    ["ViridianCity:1"] = "REGION_VIRIDIAN_CITY",
    ["ViridianCity:2"] = "REGION_VIRIDIAN_CITY",
    ["ViridianCity:3"] = "REGION_VIRIDIAN_CITY",
    ["ViridianCity:4"] = "REGION_VIRIDIAN_CITY",
    ["ViridianCity:5"] = "REGION_VIRIDIAN_CITY",
}

-- FlyRegion id -> unlock token (the pack's flyunlock_/free_fly_ suffix). Order matches the
-- apworld's data.fly_regions ids, i.e. slot_data.fly_destinations[id] is this town's dest.
FLY_REGION_TOKENS = {
    [1] = "NewBark",
    [2] = "Cherrygrove",
    [3] = "Violet",
    [4] = "Azalea",
    [5] = "Goldenrod",
    [6] = "Ecruteak",
    [7] = "Olivine",
    [8] = "Cianwood",
    [9] = "Mahogany",
    [10] = "LakeOfRage",
    [11] = "Blackthorn",
    [12] = "SilverCave",
    [13] = "Pallet",
    [14] = "Viridian",
    [15] = "Pewter",
    [16] = "Cerulean",
    [17] = "Vermilion",
    [18] = "Lavender",
    [19] = "Celadon",
    [20] = "Saffron",
    [21] = "Fuchsia",
    [22] = "Cinnabar",
    [23] = "IndigoPlateau",
}

-- token -> vanilla destination region (used as the default when fly destinations aren't
-- randomized, so behaviour is unchanged). Equals each FlyRegion's exit_region.
FLY_VANILLA_REGIONS = {
    ["NewBark"] = "REGION_NEW_BARK_TOWN",
    ["Cherrygrove"] = "REGION_CHERRYGROVE_CITY",
    ["Violet"] = "REGION_VIOLET_CITY",
    ["Azalea"] = "REGION_AZALEA_TOWN",
    ["Goldenrod"] = "REGION_GOLDENROD_CITY",
    ["Ecruteak"] = "REGION_ECRUTEAK_CITY",
    ["Olivine"] = "REGION_OLIVINE_CITY",
    ["Cianwood"] = "REGION_CIANWOOD_CITY",
    ["Mahogany"] = "REGION_MAHOGANY_TOWN",
    ["LakeOfRage"] = "REGION_LAKE_OF_RAGE",
    ["Blackthorn"] = "REGION_BLACKTHORN_CITY",
    ["SilverCave"] = "REGION_SILVER_CAVE_OUTSIDE",
    ["Pallet"] = "REGION_PALLET_TOWN",
    ["Viridian"] = "REGION_VIRIDIAN_CITY",
    ["Pewter"] = "REGION_PEWTER_CITY",
    ["Cerulean"] = "REGION_CERULEAN_CITY",
    ["Vermilion"] = "REGION_VERMILION_CITY",
    ["Lavender"] = "REGION_LAVENDER_TOWN",
    ["Celadon"] = "REGION_CELADON_CITY",
    ["Saffron"] = "REGION_SAFFRON_CITY",
    ["Fuchsia"] = "REGION_FUCHSIA_CITY",
    ["Cinnabar"] = "REGION_CINNABAR_ISLAND",
    ["IndigoPlateau"] = "REGION_ROUTE_23",
}

-- set vanilla in init of the tracker. Gets overwritten in onClear later with real values.
for token, region in pairs(FLY_VANILLA_REGIONS) do
    FLY_DESTINATIONS[token] = region
end

-- token -> town overlay icon (reused from the flyunlock item art) for the destination display.
FLY_ICON_OVERLAYS = {
    ["NewBark"]       = "images/items/flyunlocks/fly_newbarktown.png",
    ["Cherrygrove"]   = "images/items/flyunlocks/fly_cherrygrovecity.png",
    ["Violet"]        = "images/items/flyunlocks/fly_violetcity.png",
    ["Azalea"]        = "images/items/flyunlocks/fly_azaleatown.png",
    ["Goldenrod"]     = "images/items/flyunlocks/fly_goldenrodcity.png",
    ["Ecruteak"]      = "images/items/flyunlocks/fly_ecruteakcity.png",
    ["Olivine"]       = "images/items/flyunlocks/fly_olivinecity.png",
    ["Cianwood"]      = "images/items/flyunlocks/fly_cianwoodcity.png",
    ["Mahogany"]      = "images/items/flyunlocks/fly_mahoganytown.png",
    ["LakeOfRage"]    = "images/items/flyunlocks/fly_lakeofrage.png",
    ["Blackthorn"]    = "images/items/flyunlocks/fly_blackthorncity.png",
    ["SilverCave"]    = "images/items/flyunlocks/fly_silvercave.png",
    ["Pallet"]        = "images/items/flyunlocks/fly_pallettown.png",
    ["Viridian"]      = "images/items/flyunlocks/fly_viridiancity.png",
    ["Pewter"]        = "images/items/flyunlocks/fly_pewtercity.png",
    ["Cerulean"]      = "images/items/flyunlocks/fly_ceruleancity.png",
    ["Vermilion"]     = "images/items/flyunlocks/fly_vermilioncity.png",
    ["Lavender"]      = "images/items/flyunlocks/fly_lavendertown.png",
    ["Celadon"]       = "images/items/flyunlocks/fly_celadoncity.png",
    ["Saffron"]       = "images/items/flyunlocks/fly_saffroncity.png",
    ["Fuchsia"]       = "images/items/flyunlocks/fly_fuchsiacity.png",
    ["Cinnabar"]      = "images/items/flyunlocks/fly_cinnabarisland.png",
    ["IndigoPlateau"] = "images/items/flyunlocks/fly_indigoplateau.png",
}

-- Curated overrides for any region whose auto-derived label reads badly; wins over the deriver.
FLY_REGION_NAME_OVERRIDES = {}

local FLY_NAME_SMALL = { ["of"] = true, ["and"] = true, ["the"] = true }
local FLY_NAME_UPPER = { ne = true, nw = true, se = true, sw = true }

--- Title-cases an underscore-separated chunk (small words stay lowercase mid-string,
--- compass abbreviations stay upper).
---@param s string
---@return string
local function flyTitleWords(s)
    local out = {}
    for word in string.gmatch(s, "[^_]+") do
        local lw = string.lower(word)
        if FLY_NAME_UPPER[lw] then
            out[#out + 1] = string.upper(word)
        elseif FLY_NAME_SMALL[lw] and #out > 0 then
            out[#out + 1] = lw
        else
            out[#out + 1] = lw:sub(1, 1):upper() .. lw:sub(2)
        end
    end
    return table.concat(out, " ")
end

--- Human-readable destination label for a region token, e.g.
---   REGION_CERULEAN_CITY:GYM_ENTRANCE -> "Cerulean City (Gym Entrance)".
---@param region string|nil
---@return string
function FlyRegionPrettyName(region)
    if not region then return "????" end
    local override = FLY_REGION_NAME_OVERRIDES[region]
    if override then return override end
    local body = region:gsub("^REGION_", "")
    local base, sub = body:match("^([^:]+):(.+)$")
    if not base then
        return flyTitleWords(body)
    end
    return flyTitleWords(base) .. " (" .. flyTitleWords(sub:gsub(":", "_")) .. ")"
end

