-- Encounter leaves: one dead-end node per wild-encounter TABLE, attached from every
-- region whose regions.json `wild_encounters` names that table. Generated from
-- external_files/regions.json -- regenerate rather than hand-edit.
--
-- WHY A SHARED LEAF: an encounter table is fishable/catchable from many regions, so the
-- check is reachable if ANY of them is. Attaching the same leaf name from N regions makes
-- exactly that OR-node: canreach.lua:102 reuses NAMED_NODES[name], so every attach point
-- feeds one node. It also means a table sitting on a :SURF/:WATER sub-region inherits that
-- sub-region's Surf gate straight from the graph edge -- no $can_surf_* rule in the JSON.
--
-- THESE MUST STAY DEAD ENDS. Never give one an outgoing edge: every region that feeds a
-- leaf would become mutually reachable through it (a teleport hub) and the logic silently
-- opens up. Only ever connect_one_way INTO them.
--
-- LOAD ORDER MATTERS: init.lua loads this BEFORE connections_darkareas.lua, the opposite of
-- check_leafs.lua. A shared leaf can straddle dark and lit regions (FISHING_Ocean: 1 dark
-- attach point, 23 lit), so a per-section $dark in the JSON would be wrong -- it would
-- demand Flash everywhere. Loading before the dark pass lets gate_region_exits AND the
-- flash gate onto just the attach edges that leave a dark region. Move this line after
-- connections_darkareas.lua and every dark encounter silently loses its Flash requirement.
--
-- Bind from a location JSON with e.g.:
--     "access_rules": ["^$CanReach|FISHING_LAKE"]
--
-- NOTE on headbutt Route: special_encounters.json used to carry a comment saying Route 34
-- and Route 35 are "not in logic because there aren't enough trees". regions.json's
-- headbutt `Route` table already excludes both, so that intent is preserved by the data.

-- === FISHING_Dratini  (5 regions) ===
NAMED_NODES["REGION_DRAGONS_DEN_B1F:CENTER"]:connect_one_way("FISHING_Dratini")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:NORTH"]:connect_one_way("FISHING_Dratini")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:SOUTH"]:connect_one_way("FISHING_Dratini")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:SOUTHEAST"]:connect_one_way("FISHING_Dratini")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:WEST"]:connect_one_way("FISHING_Dratini")

-- === FISHING_Dratini_2  (2 regions) ===
NAMED_NODES["REGION_ROUTE_23_RESTORED:SURF"]:connect_one_way("FISHING_Dratini_2")
REGION_ROUTE_45:connect_one_way("FISHING_Dratini_2")

-- === FISHING_Gyarados  (2 regions) ===
REGION_FUCHSIA_CITY:connect_one_way("FISHING_Gyarados")
REGION_LAKE_OF_RAGE:connect_one_way("FISHING_Gyarados")

-- === FISHING_Lake  (38 regions) ===
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:NORTHEAST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:NORTHWEST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:SOUTHEAST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:NORTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:WEST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:NORTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:SOUTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:WATERFALL_ISLAND"]:connect_one_way("FISHING_Lake")
REGION_MOUNT_MORTAR_2F_INSIDE:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:NORTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:SOUTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:SOUTHWEST"]:connect_one_way("FISHING_Lake")
REGION_MOUNT_MORTAR_B1F:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_MOUNT_MORTAR_B1F:SOUTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_ROUTE_10_NORTH:SURF"]:connect_one_way("FISHING_Lake")
REGION_ROUTE_24:connect_one_way("FISHING_Lake")
REGION_ROUTE_25:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_ROUTE_42:CENTER"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_ROUTE_42:EAST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_ROUTE_42:WEST"]:connect_one_way("FISHING_Lake")
REGION_ROUTE_9:connect_one_way("FISHING_Lake")
REGION_SILVER_CAVE_ROOM_2:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:EAST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:WEST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:WEST_ITEM"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:CENTER"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:ENTRANCE"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:WEST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SLOWPOKE_WELL_B2F:CENTER"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_SLOWPOKE_WELL_B2F:ISLANDS"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_TOHJO_FALLS:EAST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_TOHJO_FALLS:WEST"]:connect_one_way("FISHING_Lake")
REGION_UNION_CAVE_1F:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_UNION_CAVE_1F:SOUTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_UNION_CAVE_B1F:CENTER"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_UNION_CAVE_B1F:NORTH"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_UNION_CAVE_B1F:SOUTHEAST"]:connect_one_way("FISHING_Lake")
NAMED_NODES["REGION_UNION_CAVE_B1F:SOUTHWEST"]:connect_one_way("FISHING_Lake")

-- === FISHING_Ocean  (24 regions) ===
REGION_CINNABAR_ISLAND:connect_one_way("FISHING_Ocean")
REGION_FLOODED_MINE:connect_one_way("FISHING_Ocean")
REGION_NEW_BARK_TOWN:connect_one_way("FISHING_Ocean")
REGION_OLIVINE_PORT:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_OLIVINE_PORT:TICKET"]:connect_one_way("FISHING_Ocean")
REGION_PALLET_TOWN:connect_one_way("FISHING_Ocean")
REGION_ROUTE_20:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_20:SEAFOAM"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_21:NORTH"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_21:SOUTH"]:connect_one_way("FISHING_Ocean")
REGION_ROUTE_26:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_27:CENTER"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_27:EAST"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_27:WEST"]:connect_one_way("FISHING_Ocean")
REGION_ROUTE_41:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_41:NE_ISLAND"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_41:NW_ISLAND"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_41:SE_ISLAND"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_41:SE_ISLAND:ITEM"]:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_ROUTE_41:SW_ISLAND"]:connect_one_way("FISHING_Ocean")
REGION_VERMILION_CITY:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_VERMILION_CITY:GYM_ENTRANCE"]:connect_one_way("FISHING_Ocean")
REGION_VERMILION_PORT:connect_one_way("FISHING_Ocean")
NAMED_NODES["REGION_VERMILION_PORT:TICKET"]:connect_one_way("FISHING_Ocean")

-- === FISHING_Pond  (19 regions) ===
REGION_BLACKTHORN_CITY:connect_one_way("FISHING_Pond")
NAMED_NODES["REGION_BLACKTHORN_CITY:DRAGONS_DEN_ENTRANCE"]:connect_one_way("FISHING_Pond")
REGION_ECRUTEAK_CITY:connect_one_way("FISHING_Pond")
NAMED_NODES["REGION_ILEX_FOREST:NORTH"]:connect_one_way("FISHING_Pond")
REGION_ROUTE_22:connect_one_way("FISHING_Pond")
REGION_ROUTE_28:connect_one_way("FISHING_Pond")
REGION_ROUTE_30:connect_one_way("FISHING_Pond")
REGION_ROUTE_31:connect_one_way("FISHING_Pond")
REGION_ROUTE_35:connect_one_way("FISHING_Pond")
REGION_ROUTE_43:connect_one_way("FISHING_Pond")
REGION_ROUTE_44:connect_one_way("FISHING_Pond")
NAMED_NODES["REGION_ROUTE_44:WATER"]:connect_one_way("FISHING_Pond")
REGION_ROUTE_6:connect_one_way("FISHING_Pond")
REGION_RUINS_OF_ALPH_OUTSIDE:connect_one_way("FISHING_Pond")
NAMED_NODES["REGION_RUINS_OF_ALPH_OUTSIDE:SOUTH"]:connect_one_way("FISHING_Pond")
REGION_SILVER_CAVE_OUTSIDE:connect_one_way("FISHING_Pond")
NAMED_NODES["REGION_SILVER_CAVE_OUTSIDE:SURF"]:connect_one_way("FISHING_Pond")
REGION_VIOLET_CITY:connect_one_way("FISHING_Pond")
REGION_VIRIDIAN_CITY:connect_one_way("FISHING_Pond")

-- === FISHING_Qwilfish  (4 regions) ===
NAMED_NODES["REGION_ROUTE_12:NORTH"]:connect_one_way("FISHING_Qwilfish")
NAMED_NODES["REGION_ROUTE_12:SOUTH"]:connect_one_way("FISHING_Qwilfish")
REGION_ROUTE_13:connect_one_way("FISHING_Qwilfish")
NAMED_NODES["REGION_ROUTE_32:SOUTH"]:connect_one_way("FISHING_Qwilfish")

-- === FISHING_Shore  (9 regions) ===
REGION_CHERRYGROVE_CITY:connect_one_way("FISHING_Shore")
NAMED_NODES["REGION_CHERRYGROVE_CITY:FLOODED_MINE_ENTRANCE"]:connect_one_way("FISHING_Shore")
REGION_CIANWOOD_CITY:connect_one_way("FISHING_Shore")
REGION_OLIVINE_CITY:connect_one_way("FISHING_Shore")
REGION_ROUTE_19:connect_one_way("FISHING_Shore")
NAMED_NODES["REGION_ROUTE_19:SHORE"]:connect_one_way("FISHING_Shore")
REGION_ROUTE_34:connect_one_way("FISHING_Shore")
REGION_ROUTE_40:connect_one_way("FISHING_Shore")
NAMED_NODES["REGION_UNION_CAVE_B2F:SURF"]:connect_one_way("FISHING_Shore")

-- === FISHING_WhirlIslands  (8 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:LUGIA_CHAMBER_ENTRANCE"]:connect_one_way("FISHING_WhirlIslands")
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:NORTH"]:connect_one_way("FISHING_WhirlIslands")
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:SOUTH"]:connect_one_way("FISHING_WhirlIslands")
NAMED_NODES["REGION_WHIRL_ISLAND_LUGIA_CHAMBER:WATER"]:connect_one_way("FISHING_WhirlIslands")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:NORTHEAST"]:connect_one_way("FISHING_WhirlIslands")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:NORTHWEST"]:connect_one_way("FISHING_WhirlIslands")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:SOUTHEAST"]:connect_one_way("FISHING_WhirlIslands")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:SOUTHWEST"]:connect_one_way("FISHING_WhirlIslands")

-- === GRASS_BURNED_TOWER_1F  (1 region) ===
REGION_BURNED_TOWER_1F:connect_one_way("GRASS_BURNED_TOWER_1F")

-- === GRASS_BURNED_TOWER_B1F  (1 region) ===
REGION_BURNED_TOWER_B1F:connect_one_way("GRASS_BURNED_TOWER_B1F")

-- === GRASS_DARK_CAVE_BLACKTHORN_ENTRANCE  (4 regions) ===
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:NORTHEAST"]:connect_one_way("GRASS_DARK_CAVE_BLACKTHORN_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:NORTHWEST"]:connect_one_way("GRASS_DARK_CAVE_BLACKTHORN_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:SOUTHEAST"]:connect_one_way("GRASS_DARK_CAVE_BLACKTHORN_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:SOUTHWEST"]:connect_one_way("GRASS_DARK_CAVE_BLACKTHORN_ENTRANCE")

-- === GRASS_DARK_CAVE_VIOLET_ENTRANCE  (4 regions) ===
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:NORTH"]:connect_one_way("GRASS_DARK_CAVE_VIOLET_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:NORTHEAST"]:connect_one_way("GRASS_DARK_CAVE_VIOLET_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:SOUTHEAST"]:connect_one_way("GRASS_DARK_CAVE_VIOLET_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:WEST"]:connect_one_way("GRASS_DARK_CAVE_VIOLET_ENTRANCE")

-- === GRASS_DIGLETTS_CAVE  (3 regions) ===
REGION_DIGLETTS_CAVE:connect_one_way("GRASS_DIGLETTS_CAVE")
NAMED_NODES["REGION_DIGLETTS_CAVE:NORTH_ENTRANCE"]:connect_one_way("GRASS_DIGLETTS_CAVE")
NAMED_NODES["REGION_DIGLETTS_CAVE:SOUTH_ENTRANCE"]:connect_one_way("GRASS_DIGLETTS_CAVE")

-- === GRASS_FLOODED_MINE  (3 regions) ===
REGION_FLOODED_MINE:connect_one_way("GRASS_FLOODED_MINE")
NAMED_NODES["REGION_FLOODED_MINE:NORTH_ENTRANCE"]:connect_one_way("GRASS_FLOODED_MINE")
NAMED_NODES["REGION_FLOODED_MINE:SOUTH_ENTRANCE"]:connect_one_way("GRASS_FLOODED_MINE")

-- === GRASS_ICE_PATH_1F  (2 regions) ===
NAMED_NODES["REGION_ICE_PATH_1F:EAST"]:connect_one_way("GRASS_ICE_PATH_1F")
NAMED_NODES["REGION_ICE_PATH_1F:WEST"]:connect_one_way("GRASS_ICE_PATH_1F")

-- === GRASS_ICE_PATH_B1F  (3 regions) ===
NAMED_NODES["REGION_ICE_PATH_B1F:NORTH"]:connect_one_way("GRASS_ICE_PATH_B1F")
NAMED_NODES["REGION_ICE_PATH_B1F:NORTH:STRENGTH"]:connect_one_way("GRASS_ICE_PATH_B1F")
NAMED_NODES["REGION_ICE_PATH_B1F:SOUTH"]:connect_one_way("GRASS_ICE_PATH_B1F")

-- === GRASS_ICE_PATH_B2F_BLACKTHORN_SIDE  (1 region) ===
REGION_ICE_PATH_B2F_BLACKTHORN_SIDE:connect_one_way("GRASS_ICE_PATH_B2F_BLACKTHORN_SIDE")

-- === GRASS_ICE_PATH_B2F_MAHOGANY_SIDE  (2 regions) ===
REGION_ICE_PATH_B2F_MAHOGANY_SIDE:connect_one_way("GRASS_ICE_PATH_B2F_MAHOGANY_SIDE")
NAMED_NODES["REGION_ICE_PATH_B2F_MAHOGANY_SIDE:MIDDLE"]:connect_one_way("GRASS_ICE_PATH_B2F_MAHOGANY_SIDE")

-- === GRASS_ICE_PATH_B3F  (1 region) ===
REGION_ICE_PATH_B3F:connect_one_way("GRASS_ICE_PATH_B3F")

-- === GRASS_ILEX_FOREST  (2 regions) ===
NAMED_NODES["REGION_ILEX_FOREST:NORTH"]:connect_one_way("GRASS_ILEX_FOREST")
NAMED_NODES["REGION_ILEX_FOREST:SOUTH"]:connect_one_way("GRASS_ILEX_FOREST")

-- === GRASS_MOUNT_MOON  (1 region) ===
REGION_MOUNT_MOON:connect_one_way("GRASS_MOUNT_MOON")

-- === GRASS_MOUNT_MORTAR_1F_INSIDE  (3 regions) ===
REGION_MOUNT_MORTAR_1F_INSIDE:connect_one_way("GRASS_MOUNT_MORTAR_1F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_INSIDE:NORTH"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_INSIDE:SOUTH"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_INSIDE")

-- === GRASS_MOUNT_MORTAR_1F_OUTSIDE  (9 regions) ===
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:EAST"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:NORTH"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:SOUTH"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:SOUTHEAST"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:SOUTHEAST:ENTRANCE"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:SOUTHWEST"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:SOUTHWEST:ENTRANCE"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:WATERFALL_ISLAND"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:WEST"]:connect_one_way("GRASS_MOUNT_MORTAR_1F_OUTSIDE")

-- === GRASS_MOUNT_MORTAR_2F_INSIDE  (4 regions) ===
REGION_MOUNT_MORTAR_2F_INSIDE:connect_one_way("GRASS_MOUNT_MORTAR_2F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:NORTH"]:connect_one_way("GRASS_MOUNT_MORTAR_2F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:SOUTH"]:connect_one_way("GRASS_MOUNT_MORTAR_2F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:SOUTHWEST"]:connect_one_way("GRASS_MOUNT_MORTAR_2F_INSIDE")

-- === GRASS_MOUNT_MORTAR_B1F  (3 regions) ===
REGION_MOUNT_MORTAR_B1F:connect_one_way("GRASS_MOUNT_MORTAR_B1F")
NAMED_NODES["REGION_MOUNT_MORTAR_B1F:NORTHWEST"]:connect_one_way("GRASS_MOUNT_MORTAR_B1F")
NAMED_NODES["REGION_MOUNT_MORTAR_B1F:SOUTH"]:connect_one_way("GRASS_MOUNT_MORTAR_B1F")

-- === GRASS_NATIONAL_PARK  (1 region) ===
REGION_NATIONAL_PARK:connect_one_way("GRASS_NATIONAL_PARK")

-- === GRASS_ROCK_TUNNEL_1F  (3 regions) ===
NAMED_NODES["REGION_ROCK_TUNNEL_1F:NORTHEAST"]:connect_one_way("GRASS_ROCK_TUNNEL_1F")
NAMED_NODES["REGION_ROCK_TUNNEL_1F:NORTHWEST"]:connect_one_way("GRASS_ROCK_TUNNEL_1F")
NAMED_NODES["REGION_ROCK_TUNNEL_1F:SOUTH"]:connect_one_way("GRASS_ROCK_TUNNEL_1F")

-- === GRASS_ROCK_TUNNEL_B1F  (2 regions) ===
NAMED_NODES["REGION_ROCK_TUNNEL_B1F:EAST"]:connect_one_way("GRASS_ROCK_TUNNEL_B1F")
NAMED_NODES["REGION_ROCK_TUNNEL_B1F:WEST"]:connect_one_way("GRASS_ROCK_TUNNEL_B1F")

-- === GRASS_ROUTE_1  (1 region) ===
REGION_ROUTE_1:connect_one_way("GRASS_ROUTE_1")

-- === GRASS_ROUTE_10_NORTH  (1 region) ===
NAMED_NODES["REGION_ROUTE_10_NORTH:SURF"]:connect_one_way("GRASS_ROUTE_10_NORTH")

-- === GRASS_ROUTE_11  (1 region) ===
REGION_ROUTE_11:connect_one_way("GRASS_ROUTE_11")

-- === GRASS_ROUTE_13  (1 region) ===
NAMED_NODES["REGION_ROUTE_13:CUT"]:connect_one_way("GRASS_ROUTE_13")

-- === GRASS_ROUTE_14  (1 region) ===
NAMED_NODES["REGION_ROUTE_14:CUT"]:connect_one_way("GRASS_ROUTE_14")

-- === GRASS_ROUTE_15  (1 region) ===
REGION_ROUTE_15:connect_one_way("GRASS_ROUTE_15")

-- === GRASS_ROUTE_16  (1 region) ===
NAMED_NODES["REGION_ROUTE_16:NORTH"]:connect_one_way("GRASS_ROUTE_16")

-- === GRASS_ROUTE_17  (1 region) ===
REGION_ROUTE_17:connect_one_way("GRASS_ROUTE_17")

-- === GRASS_ROUTE_18  (1 region) ===
REGION_ROUTE_18:connect_one_way("GRASS_ROUTE_18")

-- === GRASS_ROUTE_2  (1 region) ===
NAMED_NODES["REGION_ROUTE_2:WEST"]:connect_one_way("GRASS_ROUTE_2")

-- === GRASS_ROUTE_21  (1 region) ===
NAMED_NODES["REGION_ROUTE_21:NORTH"]:connect_one_way("GRASS_ROUTE_21")

-- === GRASS_ROUTE_22  (1 region) ===
REGION_ROUTE_22:connect_one_way("GRASS_ROUTE_22")

-- === GRASS_ROUTE_23_RESTORED  (1 region) ===
NAMED_NODES["REGION_ROUTE_23_RESTORED:NORTH"]:connect_one_way("GRASS_ROUTE_23_RESTORED")

-- === GRASS_ROUTE_24  (1 region) ===
REGION_ROUTE_24:connect_one_way("GRASS_ROUTE_24")

-- === GRASS_ROUTE_25  (1 region) ===
REGION_ROUTE_25:connect_one_way("GRASS_ROUTE_25")

-- === GRASS_ROUTE_26  (1 region) ===
REGION_ROUTE_26:connect_one_way("GRASS_ROUTE_26")

-- === GRASS_ROUTE_27  (1 region) ===
NAMED_NODES["REGION_ROUTE_27:EAST"]:connect_one_way("GRASS_ROUTE_27")

-- === GRASS_ROUTE_28  (1 region) ===
REGION_ROUTE_28:connect_one_way("GRASS_ROUTE_28")

-- === GRASS_ROUTE_29  (1 region) ===
REGION_ROUTE_29:connect_one_way("GRASS_ROUTE_29")

-- === GRASS_ROUTE_3  (1 region) ===
REGION_ROUTE_3:connect_one_way("GRASS_ROUTE_3")

-- === GRASS_ROUTE_30  (2 regions) ===
REGION_ROUTE_30:connect_one_way("GRASS_ROUTE_30")
NAMED_NODES["REGION_ROUTE_30:NORTHWEST"]:connect_one_way("GRASS_ROUTE_30")

-- === GRASS_ROUTE_31  (1 region) ===
REGION_ROUTE_31:connect_one_way("GRASS_ROUTE_31")

-- === GRASS_ROUTE_32  (1 region) ===
NAMED_NODES["REGION_ROUTE_32:SOUTH"]:connect_one_way("GRASS_ROUTE_32")

-- === GRASS_ROUTE_33  (1 region) ===
REGION_ROUTE_33:connect_one_way("GRASS_ROUTE_33")

-- === GRASS_ROUTE_34  (1 region) ===
REGION_ROUTE_34:connect_one_way("GRASS_ROUTE_34")

-- === GRASS_ROUTE_35  (1 region) ===
REGION_ROUTE_35:connect_one_way("GRASS_ROUTE_35")

-- === GRASS_ROUTE_36  (2 regions) ===
NAMED_NODES["REGION_ROUTE_36:EAST"]:connect_one_way("GRASS_ROUTE_36")
NAMED_NODES["REGION_ROUTE_36:WEST"]:connect_one_way("GRASS_ROUTE_36")

-- === GRASS_ROUTE_37  (1 region) ===
REGION_ROUTE_37:connect_one_way("GRASS_ROUTE_37")

-- === GRASS_ROUTE_38  (1 region) ===
REGION_ROUTE_38:connect_one_way("GRASS_ROUTE_38")

-- === GRASS_ROUTE_39  (1 region) ===
REGION_ROUTE_39:connect_one_way("GRASS_ROUTE_39")

-- === GRASS_ROUTE_4  (1 region) ===
NAMED_NODES["REGION_ROUTE_4:EAST"]:connect_one_way("GRASS_ROUTE_4")

-- === GRASS_ROUTE_42  (1 region) ===
NAMED_NODES["REGION_ROUTE_42:EAST"]:connect_one_way("GRASS_ROUTE_42")

-- === GRASS_ROUTE_43  (1 region) ===
REGION_ROUTE_43:connect_one_way("GRASS_ROUTE_43")

-- === GRASS_ROUTE_44  (1 region) ===
NAMED_NODES["REGION_ROUTE_44:WATER"]:connect_one_way("GRASS_ROUTE_44")

-- === GRASS_ROUTE_45  (1 region) ===
REGION_ROUTE_45:connect_one_way("GRASS_ROUTE_45")

-- === GRASS_ROUTE_46  (1 region) ===
NAMED_NODES["REGION_ROUTE_46:SOUTH"]:connect_one_way("GRASS_ROUTE_46")

-- === GRASS_ROUTE_5  (1 region) ===
REGION_ROUTE_5:connect_one_way("GRASS_ROUTE_5")

-- === GRASS_ROUTE_6  (1 region) ===
REGION_ROUTE_6:connect_one_way("GRASS_ROUTE_6")

-- === GRASS_ROUTE_7  (1 region) ===
REGION_ROUTE_7:connect_one_way("GRASS_ROUTE_7")

-- === GRASS_ROUTE_8  (1 region) ===
NAMED_NODES["REGION_ROUTE_8:CUT"]:connect_one_way("GRASS_ROUTE_8")

-- === GRASS_ROUTE_9  (1 region) ===
REGION_ROUTE_9:connect_one_way("GRASS_ROUTE_9")

-- === GRASS_RUINS_OF_ALPH_INNER_CHAMBER  (1 region) ===
REGION_RUINS_OF_ALPH_INNER_CHAMBER:connect_one_way("GRASS_RUINS_OF_ALPH_INNER_CHAMBER")

-- === GRASS_RUINS_OF_ALPH_OUTSIDE  (1 region) ===
NAMED_NODES["REGION_RUINS_OF_ALPH_OUTSIDE:WEST"]:connect_one_way("GRASS_RUINS_OF_ALPH_OUTSIDE")

-- === GRASS_SILVER_CAVE_ITEM_ROOMS  (2 regions) ===
NAMED_NODES["REGION_SILVER_CAVE_ITEM_ROOMS:EAST"]:connect_one_way("GRASS_SILVER_CAVE_ITEM_ROOMS")
NAMED_NODES["REGION_SILVER_CAVE_ITEM_ROOMS:WEST"]:connect_one_way("GRASS_SILVER_CAVE_ITEM_ROOMS")

-- === GRASS_SILVER_CAVE_OUTSIDE  (2 regions) ===
REGION_SILVER_CAVE_OUTSIDE:connect_one_way("GRASS_SILVER_CAVE_OUTSIDE")
NAMED_NODES["REGION_SILVER_CAVE_OUTSIDE:SURF"]:connect_one_way("GRASS_SILVER_CAVE_OUTSIDE")

-- === GRASS_SILVER_CAVE_ROOM_1  (1 region) ===
REGION_SILVER_CAVE_ROOM_1:connect_one_way("GRASS_SILVER_CAVE_ROOM_1")

-- === GRASS_SILVER_CAVE_ROOM_2  (4 regions) ===
REGION_SILVER_CAVE_ROOM_2:connect_one_way("GRASS_SILVER_CAVE_ROOM_2")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:EAST"]:connect_one_way("GRASS_SILVER_CAVE_ROOM_2")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:WEST"]:connect_one_way("GRASS_SILVER_CAVE_ROOM_2")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:WEST_ITEM"]:connect_one_way("GRASS_SILVER_CAVE_ROOM_2")

-- === GRASS_SILVER_CAVE_ROOM_3  (1 region) ===
REGION_SILVER_CAVE_ROOM_3:connect_one_way("GRASS_SILVER_CAVE_ROOM_3")

-- === GRASS_SLOWPOKE_WELL_B1F  (4 regions) ===
REGION_SLOWPOKE_WELL_B1F:connect_one_way("GRASS_SLOWPOKE_WELL_B1F")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:CENTER"]:connect_one_way("GRASS_SLOWPOKE_WELL_B1F")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:ENTRANCE"]:connect_one_way("GRASS_SLOWPOKE_WELL_B1F")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:WEST"]:connect_one_way("GRASS_SLOWPOKE_WELL_B1F")

-- === GRASS_SLOWPOKE_WELL_B2F  (2 regions) ===
NAMED_NODES["REGION_SLOWPOKE_WELL_B2F:CENTER"]:connect_one_way("GRASS_SLOWPOKE_WELL_B2F")
NAMED_NODES["REGION_SLOWPOKE_WELL_B2F:ISLANDS"]:connect_one_way("GRASS_SLOWPOKE_WELL_B2F")

-- === GRASS_SPROUT_TOWER_2F  (2 regions) ===
REGION_SPROUT_TOWER_2F:connect_one_way("GRASS_SPROUT_TOWER_2F")
NAMED_NODES["REGION_SPROUT_TOWER_2F:OUTER"]:connect_one_way("GRASS_SPROUT_TOWER_2F")

-- === GRASS_SPROUT_TOWER_3F  (1 region) ===
REGION_SPROUT_TOWER_3F:connect_one_way("GRASS_SPROUT_TOWER_3F")

-- === GRASS_TIN_TOWER_2F  (1 region) ===
REGION_TIN_TOWER_2F:connect_one_way("GRASS_TIN_TOWER_2F")

-- === GRASS_TIN_TOWER_3F  (1 region) ===
REGION_TIN_TOWER_3F:connect_one_way("GRASS_TIN_TOWER_3F")

-- === GRASS_TIN_TOWER_4F  (1 region) ===
REGION_TIN_TOWER_4F:connect_one_way("GRASS_TIN_TOWER_4F")

-- === GRASS_TIN_TOWER_5F  (4 regions) ===
REGION_TIN_TOWER_5F:connect_one_way("GRASS_TIN_TOWER_5F")
NAMED_NODES["REGION_TIN_TOWER_5F:SOUTH"]:connect_one_way("GRASS_TIN_TOWER_5F")
NAMED_NODES["REGION_TIN_TOWER_5F:SOUTHEAST"]:connect_one_way("GRASS_TIN_TOWER_5F")
NAMED_NODES["REGION_TIN_TOWER_5F:SOUTHWEST"]:connect_one_way("GRASS_TIN_TOWER_5F")

-- === GRASS_TIN_TOWER_6F  (1 region) ===
REGION_TIN_TOWER_6F:connect_one_way("GRASS_TIN_TOWER_6F")

-- === GRASS_TIN_TOWER_7F  (2 regions) ===
REGION_TIN_TOWER_7F:connect_one_way("GRASS_TIN_TOWER_7F")
NAMED_NODES["REGION_TIN_TOWER_7F:CENTER"]:connect_one_way("GRASS_TIN_TOWER_7F")

-- === GRASS_TIN_TOWER_8F  (4 regions) ===
NAMED_NODES["REGION_TIN_TOWER_8F:CENTER"]:connect_one_way("GRASS_TIN_TOWER_8F")
NAMED_NODES["REGION_TIN_TOWER_8F:NORTH"]:connect_one_way("GRASS_TIN_TOWER_8F")
NAMED_NODES["REGION_TIN_TOWER_8F:SOUTH"]:connect_one_way("GRASS_TIN_TOWER_8F")
NAMED_NODES["REGION_TIN_TOWER_8F:WEST"]:connect_one_way("GRASS_TIN_TOWER_8F")

-- === GRASS_TIN_TOWER_9F  (3 regions) ===
NAMED_NODES["REGION_TIN_TOWER_9F:CENTER"]:connect_one_way("GRASS_TIN_TOWER_9F")
NAMED_NODES["REGION_TIN_TOWER_9F:NORTH"]:connect_one_way("GRASS_TIN_TOWER_9F")
NAMED_NODES["REGION_TIN_TOWER_9F:SOUTH"]:connect_one_way("GRASS_TIN_TOWER_9F")

-- === GRASS_TOHJO_FALLS  (2 regions) ===
NAMED_NODES["REGION_TOHJO_FALLS:EAST"]:connect_one_way("GRASS_TOHJO_FALLS")
NAMED_NODES["REGION_TOHJO_FALLS:WEST"]:connect_one_way("GRASS_TOHJO_FALLS")

-- === GRASS_UNION_CAVE_1F  (2 regions) ===
REGION_UNION_CAVE_1F:connect_one_way("GRASS_UNION_CAVE_1F")
NAMED_NODES["REGION_UNION_CAVE_1F:SOUTH"]:connect_one_way("GRASS_UNION_CAVE_1F")

-- === GRASS_UNION_CAVE_B1F  (5 regions) ===
NAMED_NODES["REGION_UNION_CAVE_B1F:CENTER"]:connect_one_way("GRASS_UNION_CAVE_B1F")
NAMED_NODES["REGION_UNION_CAVE_B1F:NORTH"]:connect_one_way("GRASS_UNION_CAVE_B1F")
NAMED_NODES["REGION_UNION_CAVE_B1F:SOUTHEAST"]:connect_one_way("GRASS_UNION_CAVE_B1F")
NAMED_NODES["REGION_UNION_CAVE_B1F:SOUTHWEST"]:connect_one_way("GRASS_UNION_CAVE_B1F")
NAMED_NODES["REGION_UNION_CAVE_B1F:STRENGTH"]:connect_one_way("GRASS_UNION_CAVE_B1F")

-- === GRASS_UNION_CAVE_B2F  (2 regions) ===
NAMED_NODES["REGION_UNION_CAVE_B2F:NORTH"]:connect_one_way("GRASS_UNION_CAVE_B2F")
NAMED_NODES["REGION_UNION_CAVE_B2F:SURF"]:connect_one_way("GRASS_UNION_CAVE_B2F")

-- === GRASS_VICTORY_ROAD  (7 regions) ===
NAMED_NODES["REGION_VICTORY_ROAD:1F"]:connect_one_way("GRASS_VICTORY_ROAD")
NAMED_NODES["REGION_VICTORY_ROAD:1F:ENTRANCE"]:connect_one_way("GRASS_VICTORY_ROAD")
NAMED_NODES["REGION_VICTORY_ROAD:2F"]:connect_one_way("GRASS_VICTORY_ROAD")
NAMED_NODES["REGION_VICTORY_ROAD:2F:NORTHEAST"]:connect_one_way("GRASS_VICTORY_ROAD")
NAMED_NODES["REGION_VICTORY_ROAD:2F:NORTHWEST"]:connect_one_way("GRASS_VICTORY_ROAD")
NAMED_NODES["REGION_VICTORY_ROAD:3F"]:connect_one_way("GRASS_VICTORY_ROAD")
NAMED_NODES["REGION_VICTORY_ROAD:3F:SOUTHEAST"]:connect_one_way("GRASS_VICTORY_ROAD")

-- === GRASS_WHIRL_ISLAND_B1F  (5 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_B1F:LEDGE"]:connect_one_way("GRASS_WHIRL_ISLAND_B1F")
NAMED_NODES["REGION_WHIRL_ISLAND_B1F:NORTH"]:connect_one_way("GRASS_WHIRL_ISLAND_B1F")
NAMED_NODES["REGION_WHIRL_ISLAND_B1F:NORTHEAST"]:connect_one_way("GRASS_WHIRL_ISLAND_B1F")
NAMED_NODES["REGION_WHIRL_ISLAND_B1F:SOUTHEAST"]:connect_one_way("GRASS_WHIRL_ISLAND_B1F")
NAMED_NODES["REGION_WHIRL_ISLAND_B1F:SOUTHWEST"]:connect_one_way("GRASS_WHIRL_ISLAND_B1F")

-- === GRASS_WHIRL_ISLAND_B2F  (4 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:CENTER"]:connect_one_way("GRASS_WHIRL_ISLAND_B2F")
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:LUGIA_CHAMBER_ENTRANCE"]:connect_one_way("GRASS_WHIRL_ISLAND_B2F")
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:NORTH"]:connect_one_way("GRASS_WHIRL_ISLAND_B2F")
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:SOUTH"]:connect_one_way("GRASS_WHIRL_ISLAND_B2F")

-- === GRASS_WHIRL_ISLAND_CAVE  (1 region) ===
REGION_WHIRL_ISLAND_CAVE:connect_one_way("GRASS_WHIRL_ISLAND_CAVE")

-- === GRASS_WHIRL_ISLAND_LUGIA_CHAMBER  (1 region) ===
REGION_WHIRL_ISLAND_LUGIA_CHAMBER:connect_one_way("GRASS_WHIRL_ISLAND_LUGIA_CHAMBER")

-- === GRASS_WHIRL_ISLAND_NE  (4 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_NE:CENTER"]:connect_one_way("GRASS_WHIRL_ISLAND_NE")
NAMED_NODES["REGION_WHIRL_ISLAND_NE:NORTHEAST"]:connect_one_way("GRASS_WHIRL_ISLAND_NE")
NAMED_NODES["REGION_WHIRL_ISLAND_NE:SOUTHEAST"]:connect_one_way("GRASS_WHIRL_ISLAND_NE")
NAMED_NODES["REGION_WHIRL_ISLAND_NE:WEST"]:connect_one_way("GRASS_WHIRL_ISLAND_NE")

-- === GRASS_WHIRL_ISLAND_NW  (2 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_NW:NORTH"]:connect_one_way("GRASS_WHIRL_ISLAND_NW")
NAMED_NODES["REGION_WHIRL_ISLAND_NW:SOUTH"]:connect_one_way("GRASS_WHIRL_ISLAND_NW")

-- === GRASS_WHIRL_ISLAND_SE  (1 region) ===
REGION_WHIRL_ISLAND_SE:connect_one_way("GRASS_WHIRL_ISLAND_SE")

-- === GRASS_WHIRL_ISLAND_SW  (4 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_SW:NORTHEAST"]:connect_one_way("GRASS_WHIRL_ISLAND_SW")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:NORTHWEST"]:connect_one_way("GRASS_WHIRL_ISLAND_SW")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:SOUTHEAST"]:connect_one_way("GRASS_WHIRL_ISLAND_SW")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:SOUTHWEST"]:connect_one_way("GRASS_WHIRL_ISLAND_SW")

-- === HEADBUTT_Border  (3 regions) ===
NAMED_NODES["REGION_ROUTE_27:EAST"]:connect_one_way("HEADBUTT_Border")
NAMED_NODES["REGION_ROUTE_27:WEST"]:connect_one_way("HEADBUTT_Border")
NAMED_NODES["REGION_ROUTE_32:SOUTH"]:connect_one_way("HEADBUTT_Border")

-- === HEADBUTT_Canyon  (1 region) ===
REGION_ROUTE_44:connect_one_way("HEADBUTT_Canyon")

-- === HEADBUTT_Forest  (2 regions) ===
NAMED_NODES["REGION_ILEX_FOREST:NORTH"]:connect_one_way("HEADBUTT_Forest")
NAMED_NODES["REGION_ILEX_FOREST:SOUTH"]:connect_one_way("HEADBUTT_Forest")

-- === HEADBUTT_Lake  (4 regions) ===
REGION_LAKE_OF_RAGE:connect_one_way("HEADBUTT_Lake")
NAMED_NODES["REGION_LAKE_OF_RAGE:CUT"]:connect_one_way("HEADBUTT_Lake")
NAMED_NODES["REGION_LAKE_OF_RAGE:HIDDEN_POWER_HOUSE"]:connect_one_way("HEADBUTT_Lake")
NAMED_NODES["REGION_ROUTE_43:FRUITTREE"]:connect_one_way("HEADBUTT_Lake")

-- === HEADBUTT_Route  (8 regions) ===
REGION_ROUTE_29:connect_one_way("HEADBUTT_Route")
REGION_ROUTE_30:connect_one_way("HEADBUTT_Route")
NAMED_NODES["REGION_ROUTE_30:NORTHWEST"]:connect_one_way("HEADBUTT_Route")
NAMED_NODES["REGION_ROUTE_36:EAST"]:connect_one_way("HEADBUTT_Route")
NAMED_NODES["REGION_ROUTE_36:WEST"]:connect_one_way("HEADBUTT_Route")
REGION_ROUTE_37:connect_one_way("HEADBUTT_Route")
REGION_ROUTE_38:connect_one_way("HEADBUTT_Route")
REGION_ROUTE_39:connect_one_way("HEADBUTT_Route")

-- === HEADBUTT_Town  (3 regions) ===
REGION_AZALEA_TOWN:connect_one_way("HEADBUTT_Town")
REGION_ROUTE_33:connect_one_way("HEADBUTT_Town")
NAMED_NODES["REGION_ROUTE_42:HEADBUTT"]:connect_one_way("HEADBUTT_Town")

-- === ROCK_SMASH_ANY  (5 regions) ===
REGION_CIANWOOD_CITY:connect_one_way("ROCK_SMASH_ANY")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:NORTHEAST"]:connect_one_way("ROCK_SMASH_ANY")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:SOUTHEAST"]:connect_one_way("ROCK_SMASH_ANY")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:WEST"]:connect_one_way("ROCK_SMASH_ANY")
REGION_ROUTE_40:connect_one_way("ROCK_SMASH_ANY")

-- === SURF_BLACKTHORN_CITY  (2 regions) ===
REGION_BLACKTHORN_CITY:connect_one_way("SURF_BLACKTHORN_CITY")
NAMED_NODES["REGION_BLACKTHORN_CITY:DRAGONS_DEN_ENTRANCE"]:connect_one_way("SURF_BLACKTHORN_CITY")

-- === SURF_CELADON_CITY  (1 region) ===
REGION_CELADON_CITY:connect_one_way("SURF_CELADON_CITY")

-- === SURF_CERULEAN_CITY  (1 region) ===
NAMED_NODES["REGION_CERULEAN_CITY:SURF"]:connect_one_way("SURF_CERULEAN_CITY")

-- === SURF_CHERRYGROVE_CITY  (2 regions) ===
REGION_CHERRYGROVE_CITY:connect_one_way("SURF_CHERRYGROVE_CITY")
NAMED_NODES["REGION_CHERRYGROVE_CITY:FLOODED_MINE_ENTRANCE"]:connect_one_way("SURF_CHERRYGROVE_CITY")

-- === SURF_CIANWOOD_CITY  (1 region) ===
REGION_CIANWOOD_CITY:connect_one_way("SURF_CIANWOOD_CITY")

-- === SURF_CINNABAR_ISLAND  (1 region) ===
REGION_CINNABAR_ISLAND:connect_one_way("SURF_CINNABAR_ISLAND")

-- === SURF_DARK_CAVE_BLACKTHORN_ENTRANCE  (3 regions) ===
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:NORTHEAST"]:connect_one_way("SURF_DARK_CAVE_BLACKTHORN_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:NORTHWEST"]:connect_one_way("SURF_DARK_CAVE_BLACKTHORN_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_BLACKTHORN_ENTRANCE:SOUTHEAST"]:connect_one_way("SURF_DARK_CAVE_BLACKTHORN_ENTRANCE")

-- === SURF_DARK_CAVE_VIOLET_ENTRANCE  (2 regions) ===
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:NORTH"]:connect_one_way("SURF_DARK_CAVE_VIOLET_ENTRANCE")
NAMED_NODES["REGION_DARK_CAVE_VIOLET_ENTRANCE:WEST"]:connect_one_way("SURF_DARK_CAVE_VIOLET_ENTRANCE")

-- === SURF_DRAGONS_DEN_B1F  (5 regions) ===
NAMED_NODES["REGION_DRAGONS_DEN_B1F:CENTER"]:connect_one_way("SURF_DRAGONS_DEN_B1F")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:NORTH"]:connect_one_way("SURF_DRAGONS_DEN_B1F")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:SOUTH"]:connect_one_way("SURF_DRAGONS_DEN_B1F")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:SOUTHEAST"]:connect_one_way("SURF_DRAGONS_DEN_B1F")
NAMED_NODES["REGION_DRAGONS_DEN_B1F:WEST"]:connect_one_way("SURF_DRAGONS_DEN_B1F")

-- === SURF_ECRUTEAK_CITY  (1 region) ===
REGION_ECRUTEAK_CITY:connect_one_way("SURF_ECRUTEAK_CITY")

-- === SURF_FLOODED_MINE  (1 region) ===
REGION_FLOODED_MINE:connect_one_way("SURF_FLOODED_MINE")

-- === SURF_FUCHSIA_CITY  (1 region) ===
REGION_FUCHSIA_CITY:connect_one_way("SURF_FUCHSIA_CITY")

-- === SURF_ILEX_FOREST  (1 region) ===
NAMED_NODES["REGION_ILEX_FOREST:NORTH"]:connect_one_way("SURF_ILEX_FOREST")

-- === SURF_LAKE_OF_RAGE  (1 region) ===
REGION_LAKE_OF_RAGE:connect_one_way("SURF_LAKE_OF_RAGE")

-- === SURF_MOUNT_MORTAR_1F_OUTSIDE  (3 regions) ===
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:NORTH"]:connect_one_way("SURF_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:SOUTH"]:connect_one_way("SURF_MOUNT_MORTAR_1F_OUTSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_1F_OUTSIDE:WATERFALL_ISLAND"]:connect_one_way("SURF_MOUNT_MORTAR_1F_OUTSIDE")

-- === SURF_MOUNT_MORTAR_2F_INSIDE  (4 regions) ===
REGION_MOUNT_MORTAR_2F_INSIDE:connect_one_way("SURF_MOUNT_MORTAR_2F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:NORTH"]:connect_one_way("SURF_MOUNT_MORTAR_2F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:SOUTH"]:connect_one_way("SURF_MOUNT_MORTAR_2F_INSIDE")
NAMED_NODES["REGION_MOUNT_MORTAR_2F_INSIDE:SOUTHWEST"]:connect_one_way("SURF_MOUNT_MORTAR_2F_INSIDE")

-- === SURF_MOUNT_MORTAR_B1F  (2 regions) ===
REGION_MOUNT_MORTAR_B1F:connect_one_way("SURF_MOUNT_MORTAR_B1F")
NAMED_NODES["REGION_MOUNT_MORTAR_B1F:SOUTH"]:connect_one_way("SURF_MOUNT_MORTAR_B1F")

-- === SURF_NEW_BARK_TOWN  (1 region) ===
REGION_NEW_BARK_TOWN:connect_one_way("SURF_NEW_BARK_TOWN")

-- === SURF_OLIVINE_CITY  (1 region) ===
REGION_OLIVINE_CITY:connect_one_way("SURF_OLIVINE_CITY")

-- === SURF_OLIVINE_PORT  (2 regions) ===
REGION_OLIVINE_PORT:connect_one_way("SURF_OLIVINE_PORT")
NAMED_NODES["REGION_OLIVINE_PORT:TICKET"]:connect_one_way("SURF_OLIVINE_PORT")

-- === SURF_PALLET_TOWN  (1 region) ===
REGION_PALLET_TOWN:connect_one_way("SURF_PALLET_TOWN")

-- === SURF_ROUTE_10_NORTH  (1 region) ===
NAMED_NODES["REGION_ROUTE_10_NORTH:SURF"]:connect_one_way("SURF_ROUTE_10_NORTH")

-- === SURF_ROUTE_12  (2 regions) ===
NAMED_NODES["REGION_ROUTE_12:NORTH"]:connect_one_way("SURF_ROUTE_12")
NAMED_NODES["REGION_ROUTE_12:SOUTH"]:connect_one_way("SURF_ROUTE_12")

-- === SURF_ROUTE_13  (1 region) ===
REGION_ROUTE_13:connect_one_way("SURF_ROUTE_13")

-- === SURF_ROUTE_19  (2 regions) ===
REGION_ROUTE_19:connect_one_way("SURF_ROUTE_19")
NAMED_NODES["REGION_ROUTE_19:SHORE"]:connect_one_way("SURF_ROUTE_19")

-- === SURF_ROUTE_20  (2 regions) ===
REGION_ROUTE_20:connect_one_way("SURF_ROUTE_20")
NAMED_NODES["REGION_ROUTE_20:SEAFOAM"]:connect_one_way("SURF_ROUTE_20")

-- === SURF_ROUTE_21  (2 regions) ===
NAMED_NODES["REGION_ROUTE_21:NORTH"]:connect_one_way("SURF_ROUTE_21")
NAMED_NODES["REGION_ROUTE_21:SOUTH"]:connect_one_way("SURF_ROUTE_21")

-- === SURF_ROUTE_22  (1 region) ===
REGION_ROUTE_22:connect_one_way("SURF_ROUTE_22")

-- === SURF_ROUTE_23_RESTORED  (1 region) ===
NAMED_NODES["REGION_ROUTE_23_RESTORED:SURF"]:connect_one_way("SURF_ROUTE_23_RESTORED")

-- === SURF_ROUTE_24  (1 region) ===
REGION_ROUTE_24:connect_one_way("SURF_ROUTE_24")

-- === SURF_ROUTE_25  (1 region) ===
REGION_ROUTE_25:connect_one_way("SURF_ROUTE_25")

-- === SURF_ROUTE_26  (1 region) ===
REGION_ROUTE_26:connect_one_way("SURF_ROUTE_26")

-- === SURF_ROUTE_27  (3 regions) ===
NAMED_NODES["REGION_ROUTE_27:CENTER"]:connect_one_way("SURF_ROUTE_27")
NAMED_NODES["REGION_ROUTE_27:EAST"]:connect_one_way("SURF_ROUTE_27")
NAMED_NODES["REGION_ROUTE_27:WEST"]:connect_one_way("SURF_ROUTE_27")

-- === SURF_ROUTE_28  (1 region) ===
REGION_ROUTE_28:connect_one_way("SURF_ROUTE_28")

-- === SURF_ROUTE_30  (1 region) ===
REGION_ROUTE_30:connect_one_way("SURF_ROUTE_30")

-- === SURF_ROUTE_31  (1 region) ===
REGION_ROUTE_31:connect_one_way("SURF_ROUTE_31")

-- === SURF_ROUTE_32  (1 region) ===
NAMED_NODES["REGION_ROUTE_32:SOUTH"]:connect_one_way("SURF_ROUTE_32")

-- === SURF_ROUTE_34  (1 region) ===
REGION_ROUTE_34:connect_one_way("SURF_ROUTE_34")

-- === SURF_ROUTE_35  (1 region) ===
REGION_ROUTE_35:connect_one_way("SURF_ROUTE_35")

-- === SURF_ROUTE_4  (1 region) ===
NAMED_NODES["REGION_ROUTE_4:SURF"]:connect_one_way("SURF_ROUTE_4")

-- === SURF_ROUTE_40  (2 regions) ===
REGION_ROUTE_40:connect_one_way("SURF_ROUTE_40")
NAMED_NODES["REGION_ROUTE_40:WATER"]:connect_one_way("SURF_ROUTE_40")

-- === SURF_ROUTE_41  (6 regions) ===
REGION_ROUTE_41:connect_one_way("SURF_ROUTE_41")
NAMED_NODES["REGION_ROUTE_41:NE_ISLAND"]:connect_one_way("SURF_ROUTE_41")
NAMED_NODES["REGION_ROUTE_41:NW_ISLAND"]:connect_one_way("SURF_ROUTE_41")
NAMED_NODES["REGION_ROUTE_41:SE_ISLAND"]:connect_one_way("SURF_ROUTE_41")
NAMED_NODES["REGION_ROUTE_41:SE_ISLAND:ITEM"]:connect_one_way("SURF_ROUTE_41")
NAMED_NODES["REGION_ROUTE_41:SW_ISLAND"]:connect_one_way("SURF_ROUTE_41")

-- === SURF_ROUTE_42  (3 regions) ===
NAMED_NODES["REGION_ROUTE_42:CENTER"]:connect_one_way("SURF_ROUTE_42")
NAMED_NODES["REGION_ROUTE_42:EAST"]:connect_one_way("SURF_ROUTE_42")
NAMED_NODES["REGION_ROUTE_42:WEST"]:connect_one_way("SURF_ROUTE_42")

-- === SURF_ROUTE_43  (1 region) ===
REGION_ROUTE_43:connect_one_way("SURF_ROUTE_43")

-- === SURF_ROUTE_44  (2 regions) ===
REGION_ROUTE_44:connect_one_way("SURF_ROUTE_44")
NAMED_NODES["REGION_ROUTE_44:WATER"]:connect_one_way("SURF_ROUTE_44")

-- === SURF_ROUTE_45  (1 region) ===
REGION_ROUTE_45:connect_one_way("SURF_ROUTE_45")

-- === SURF_ROUTE_6  (1 region) ===
REGION_ROUTE_6:connect_one_way("SURF_ROUTE_6")

-- === SURF_ROUTE_9  (1 region) ===
REGION_ROUTE_9:connect_one_way("SURF_ROUTE_9")

-- === SURF_RUINS_OF_ALPH_OUTSIDE  (2 regions) ===
REGION_RUINS_OF_ALPH_OUTSIDE:connect_one_way("SURF_RUINS_OF_ALPH_OUTSIDE")
NAMED_NODES["REGION_RUINS_OF_ALPH_OUTSIDE:SOUTH"]:connect_one_way("SURF_RUINS_OF_ALPH_OUTSIDE")

-- === SURF_SILVER_CAVE_OUTSIDE  (2 regions) ===
REGION_SILVER_CAVE_OUTSIDE:connect_one_way("SURF_SILVER_CAVE_OUTSIDE")
NAMED_NODES["REGION_SILVER_CAVE_OUTSIDE:SURF"]:connect_one_way("SURF_SILVER_CAVE_OUTSIDE")

-- === SURF_SILVER_CAVE_ROOM_2  (4 regions) ===
REGION_SILVER_CAVE_ROOM_2:connect_one_way("SURF_SILVER_CAVE_ROOM_2")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:EAST"]:connect_one_way("SURF_SILVER_CAVE_ROOM_2")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:WEST"]:connect_one_way("SURF_SILVER_CAVE_ROOM_2")
NAMED_NODES["REGION_SILVER_CAVE_ROOM_2:WEST_ITEM"]:connect_one_way("SURF_SILVER_CAVE_ROOM_2")

-- === SURF_SLOWPOKE_WELL_B1F  (3 regions) ===
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:CENTER"]:connect_one_way("SURF_SLOWPOKE_WELL_B1F")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:ENTRANCE"]:connect_one_way("SURF_SLOWPOKE_WELL_B1F")
NAMED_NODES["REGION_SLOWPOKE_WELL_B1F:WEST"]:connect_one_way("SURF_SLOWPOKE_WELL_B1F")

-- === SURF_SLOWPOKE_WELL_B2F  (2 regions) ===
NAMED_NODES["REGION_SLOWPOKE_WELL_B2F:CENTER"]:connect_one_way("SURF_SLOWPOKE_WELL_B2F")
NAMED_NODES["REGION_SLOWPOKE_WELL_B2F:ISLANDS"]:connect_one_way("SURF_SLOWPOKE_WELL_B2F")

-- === SURF_TOHJO_FALLS  (2 regions) ===
NAMED_NODES["REGION_TOHJO_FALLS:EAST"]:connect_one_way("SURF_TOHJO_FALLS")
NAMED_NODES["REGION_TOHJO_FALLS:WEST"]:connect_one_way("SURF_TOHJO_FALLS")

-- === SURF_UNION_CAVE_1F  (2 regions) ===
REGION_UNION_CAVE_1F:connect_one_way("SURF_UNION_CAVE_1F")
NAMED_NODES["REGION_UNION_CAVE_1F:SOUTH"]:connect_one_way("SURF_UNION_CAVE_1F")

-- === SURF_UNION_CAVE_B1F  (4 regions) ===
NAMED_NODES["REGION_UNION_CAVE_B1F:CENTER"]:connect_one_way("SURF_UNION_CAVE_B1F")
NAMED_NODES["REGION_UNION_CAVE_B1F:NORTH"]:connect_one_way("SURF_UNION_CAVE_B1F")
NAMED_NODES["REGION_UNION_CAVE_B1F:SOUTHEAST"]:connect_one_way("SURF_UNION_CAVE_B1F")
NAMED_NODES["REGION_UNION_CAVE_B1F:SOUTHWEST"]:connect_one_way("SURF_UNION_CAVE_B1F")

-- === SURF_UNION_CAVE_B2F  (1 region) ===
NAMED_NODES["REGION_UNION_CAVE_B2F:SURF"]:connect_one_way("SURF_UNION_CAVE_B2F")

-- === SURF_VERMILION_CITY  (2 regions) ===
REGION_VERMILION_CITY:connect_one_way("SURF_VERMILION_CITY")
NAMED_NODES["REGION_VERMILION_CITY:GYM_ENTRANCE"]:connect_one_way("SURF_VERMILION_CITY")

-- === SURF_VERMILION_PORT  (2 regions) ===
REGION_VERMILION_PORT:connect_one_way("SURF_VERMILION_PORT")
NAMED_NODES["REGION_VERMILION_PORT:TICKET"]:connect_one_way("SURF_VERMILION_PORT")

-- === SURF_VIOLET_CITY  (1 region) ===
REGION_VIOLET_CITY:connect_one_way("SURF_VIOLET_CITY")

-- === SURF_VIRIDIAN_CITY  (1 region) ===
REGION_VIRIDIAN_CITY:connect_one_way("SURF_VIRIDIAN_CITY")

-- === SURF_WHIRL_ISLAND_B2F  (3 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:LUGIA_CHAMBER_ENTRANCE"]:connect_one_way("SURF_WHIRL_ISLAND_B2F")
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:NORTH"]:connect_one_way("SURF_WHIRL_ISLAND_B2F")
NAMED_NODES["REGION_WHIRL_ISLAND_B2F:SOUTH"]:connect_one_way("SURF_WHIRL_ISLAND_B2F")

-- === SURF_WHIRL_ISLAND_LUGIA_CHAMBER  (1 region) ===
NAMED_NODES["REGION_WHIRL_ISLAND_LUGIA_CHAMBER:WATER"]:connect_one_way("SURF_WHIRL_ISLAND_LUGIA_CHAMBER")

-- === SURF_WHIRL_ISLAND_SW  (4 regions) ===
NAMED_NODES["REGION_WHIRL_ISLAND_SW:NORTHEAST"]:connect_one_way("SURF_WHIRL_ISLAND_SW")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:NORTHWEST"]:connect_one_way("SURF_WHIRL_ISLAND_SW")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:SOUTHEAST"]:connect_one_way("SURF_WHIRL_ISLAND_SW")
NAMED_NODES["REGION_WHIRL_ISLAND_SW:SOUTHWEST"]:connect_one_way("SURF_WHIRL_ISLAND_SW")
